### ISSUE TITLE
Option to select store for each upload

### ISSUE THREAD

**Issue by samuel-p** [eikek/sharry#1041]
It would be nice to be able to select a corresponding store for each file upload in the frontend. Of course, only if more than one enabled store was defined in the configuration.

**Comment by eikek** [comment]
May I ask what your use case is? I can't really imagine why that would be beneficial 🤔 While it is possible to do, it requires a bit work, because now the fact that there are multiple stores reaches up to the ui and users. Not really sure if we should do this tbh.

**Comment by samuel-p** [comment]
I had the case, that I wanted to share an archive with ~50GB which was to large to use the server disk. So I thought it would be nice to use S3 for only that upload. After thinking more about this, I am not sure how useful this would be at the end, because I also can switch to S3 storage completely. So I will close this for now. If anyone else has another use case for this, you are welcome to reopen it.
