### ISSUE TITLE
[Feature request] Ability to have an internal and a public facing address

### ISSUE THREAD

**Issue by FlorentLM** [eikek/sharry#1048]
Hi,

I'd like to have sharry only accessible from an internal url (I reverse proxy to my containers using `https://containername.internal.hostname.net` and have DNS records for `*.internal.hostname.net` that point to an IP from a private range), but also being able to have the download / upload links accessible from the outside (by, for instance, having `https://hostname.net/upload/aliasID`). I tried setting the `base-url` option in the conf file but of course this causes the internal access to fail.

Or am I missing something?

Thanks!

**Comment by eikek** [comment]
I think this is possible right now. If you leave `base-url` to localhost (the default value), then sharry will calculate urls based on the request. Then you can access it from different domains, in general. But you can configure the reverse proxy accordingly, to allow/disallow certain paths.

**Comment by Hely0n** [comment]
This doesn't seem to work, at least in my case. when I leave the default base-url, files cannot be uploaded over the public facing URL (Cloudflare tunnel in my case). The logs say: 

> 2024.01.30 12:41:44:0002 [io-comp...] [ERROR] sharry.restserver.RestServer.applyOrElse:48 - Error processing request!
> org.http4s.ParseFailure: Invalid URI: https://<IPv6 adress of client>/api/v2/alias/upload/<Random ID>/files/tus/Aikzz8dnHT3-W56EMyMrPAE-m9JxtTAXFiU-Ao3amuUzXT6
>              ^
> 
> expectation:
> * must end the string

Maybe IPv6 is not supported by Sharry or my docker engine?

**Comment by Hely0n** [comment]
When I set the public facing URL as base-url instead, public upload works, but I can't use the WebUI via LAN, due to CORS

**Comment by eikek** [comment]
The first error seems like the http library cannot parse the url, I suspect it doesn't understand ipv6 - can you try with ipv4? It should work when leaving the `base-url` setting to its default.

**Comment by Hely0n** [comment]
Unfortunately, I'm behind a CGNAT on IPv4. It seemed to use Ipv6 even if exposed it through cloudflare tunnel. I use Pingvin now instead and just wanted to report this bug.
