### ISSUE TITLE
FATAL: sorry, too many clients already

### ISSUE THREAD

**Issue by VNuserX** [eikek/sharry#1063]
Hi,

Got following issue using external PostgreSQL setup

```
[ERROR] sharry.restserver.RestServer.applyOrElse:43 - Error processing request!
 sharry org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
```
```
SELECT
count(*)
FROM pg_stat_activity
WHERE state = 'idle';

98
```
```
SELECT
count(*)
FROM pg_stat_activity
WHERE state = 'active';

3
```

Thanks in advance

**Comment by eikek** [comment]
That is really strange. Are there any other programs accessing the database? how is your traffic in general, how many users for sharry? What version are you using?

**Comment by VNuserX** [comment]
Sorry for delay , was checking with standard Postgres setup, it looks that Postgres operated by Percona behaves different, it opens idle connections and not able to manage close it, on different setups I did not observe similar behavior. 
As for version it is latest v1.12.1, there is only one user during development yet and postgres database operated by Percona is completely dedicated to sharry

**Comment by eikek** [comment]
Oh that is really strange. Not sure what to do about it. I'm running sharry on my home server with postgres as well. It's running for months without problems. If I'm reading correctly, it seems as if despite closing a connection, it still is around? So sharry thinks it is closed and creates a new one. Hm... one option that comes to my mind is to be able to configure the connection pool timeout and make it very long. But seems to be a quite weird thing to do. Do you see any errors in the logs of sharry? (e.g. that a connection could not be closed or something similar)

**Comment by VNuserX** [comment]
It looks like, it suppose to be closed, but it left, one of solution is to set "idle_session_timeout" as by default it is disabled, but would be great to get understanding of such behavior!

Also regarding "erros" in logs - got lots of 

```
[io-comp...] [ERROR] sharry.restserver.RestServer.applyOrElse:43 - Error processing request!
java.io.IOException: Connection reset by peer
``` 

But process is always finished
Could be related

**Comment by eikek** [comment]
The error seems to be caused by not being able to create another connection. Do you have anything in between postgres and sharry? Perhaps something in between "removes" the connection so that when sharry closes it, it doesn't really get to postgres.

**Comment by VNuserX** [comment]
NO, only postgres runned by percona. Thanks for comments , will check what could cause such behavior

**Comment by VNuserX** [comment]
W e did tons of research, we found that once we put traffic via cloudflare, we start having upload issues, download works well!
Trace logging did not give add value

Could you please advise?
Thanks in advance

**Comment by eikek** [comment]
Sorry for the delay. I'm afraid I can't really help here. Not sure what cloudflare does. If it removes request headers that would break the uploads. When uploading parts of the file, request headers are used to transport the chunk metadata (size, number etc). Is this possible?

**Comment by VNuserX** [comment]
Thanks for support a lot!
