### ISSUE TITLE
Feature Request: update alias ID from API

### ISSUE THREAD

**Issue by sakshamchawla** [eikek/sharry#1089]
According to the documentation, the current REST API allows to create an alias through the REST API, and returns the alias ID. Requesting a feature to specify or update the alias ID

**Comment by eikek** [comment]
It is possible via the api (everything from the webui is done via the rest api), I think it's here: https://eikek.github.io/sharry/openapi/sharry-openapi.html#tag/Alias/operation/sec-alias-id-post

**Comment by sakshamchawla** [comment]
Thanks for link to the OpenAPI. I was just going through the [documentation site](https://eikek.github.io/sharry/doc/rest)
