### ISSUE TITLE
[feature request] Allow proxy authorisation

### ISSUE THREAD

**Issue by ekamil** [eikek/sharry#1168]
Hi,
I deployed sharry behind a traefik+authelia proxy setup. I'd like to centralise my auth needs in authelia.

### Background
Access to sharry is possible only via traefik and it's configured to use authelia as authentication/authorisation middleware.
From the point of view of the service behind proxy this looks like adding a set of headers, that's what I get:
```
Remote-Email: user@example.com
Remote-Groups: admins,users
Remote-Name: user
Remote-User: user
```

### Request
I'd like to be able to tell sharry to trust some of these headers for authentication.
```
auth {
      proxy = {
        enabled = true
        # HTTP Header name that will contain the username
        user-name-header = Remote-Name
        # HTTP Header name that will contain the email (optional)
        user-email-header = Remote-Email
        # Set to `true` to enable auto sign up of users
        auto-sign-up = true
      }
    }
```

I think [Grafana's docs](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/auth-proxy/#configure-auth-proxy-authentication) give a good impression of how that's supposed to work.

### Options
`auto-sign-up` would be nice for a better out of the box experience in setups like mine, but I can live without it.

### Security/Issues
- admin rights - I'd rather not have the option to `auto-sign-up` admin users 
- interaction with other providers - no idea how that should work 🙈 
- such setup 100% depends on proper configuration of a proxy

**Comment by eikek** [comment]
Hi @ekamil , thanks for this proposal. I see your point. I think that should be good to add. If someone uses this feature, it simply means sharry is trusting this information and responsibility for security is somewhere else ☺️ Since I'm a bit busy right now, it might take a while until this arrives, though.

**Comment by raku-cat** [comment]
Thought I would comment here that Authelia actually supports oauth/oidc, currently figuring out the specifics, will update this comment with an example once I get it working :).
