### ISSUE TITLE
multi drops in "Drop files here"-zone not possible

### ISSUE THREAD

**Issue by hoedlmoser** [eikek/sharry#117]
every time I add some files (e.g. from other directory) by dropping into "Drop files here"-zone, files dropped before get cleared. of course I could drop, submit, drop, submit, drop, submit, ... but for easy workflow would be nice if multidrop is supported and only one final submit needed.

**Comment by eikek** [comment]
Thank you @hoedlmoser for reporting. Yes, this is really inconvenient! I'll fix this for the next release.
