### ISSUE TITLE
/opt/sharry.conf Permission Denied in Docker

### ISSUE THREAD

**Issue by harrythezomby** [eikek/sharry#1228]
Hey guys,
I was just wondering if anyone knows how to fix this error when trying to use the Sharry docker compose. It says /opt/sharry.conf permission denied - am i missing something here?

![image](https://github.com/eikek/sharry/assets/69672592/67051625-d220-412a-a682-f59408a02ae0)

**Comment by harrythezomby** [comment]
Ahhh just fixed it - turns out i forgot to add a :z to the end of` ${PWD}/sharry.conf:/opt/sharry.conf` since I'm using SELinux... Silly me!

**Comment by eikek** [comment]
Can be closed then, right?
