### ISSUE TITLE
Configuration of file upload limits

### ISSUE THREAD

**Issue by steffenbusch** [eikek/sharry#1282]
I was searching google and looking into the configuration, but I have not found where I can configure the file upload limit.
When I am on the "Create a share" page, it just says `Uploads are possible up to 1.5G.`. Where can I increase this limit?

**Comment by eikek** [comment]
You can change this in the `share` section of the config. Check the default config here: https://eikek.github.io/sharry/doc/configure#default-config  (look for share -> max-size)

**Comment by steffenbusch** [comment]
Thank you very much. Merry Christmas 🎄

**Comment by eikek** [comment]
Thank you 😄 ! Same for you!
