### ISSUE TITLE
Azure AD Authentication doesn't work with java.net.ConnectException: Connection timed out

### ISSUE THREAD

**Issue by rosswell98** [eikek/sharry#1310]
Hello, 

I implemented Sharry for some file transfers and the last step is to log in with Azure AD accounts.
The configuration seems to be OK in Sharry and Azure AD.
When we authenticate with Azure AD we fall in a loop with a final error : **Internal Error: Connection timed out**

Here the error in Sharry logs: 
> [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v2/open/auth/oauth/aad/resume?code=[REMOVED]&state=QZQfR5kGnKZ%24FTT0tneTqfOf-2Rny0qlere6TXY&session_state=454e6e99-0ac1-4f54-8197-4b5dea03987f
> 2024.01.18 15:27:57:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - service raised an error: class java.net.ConnectException
> 2024.01.18 15:27:57:0002 [io-comp...] [ERROR] sharry.restserver.RestServer.applyOrElse:48 - Error processing request!
> java.net.ConnectException: Connection timed out
>         at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
>         at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:256)
>         at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:202)
>         at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217)
>         at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306)
>         at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
>         at java.lang.Thread.run(Thread.java:833)
>         at delay @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.$anonfun$client$8(SocketGroupPlatform.scala:65)
>         at as @ sharry.restserver.Main$.$anonfun$run$17(Main.scala:70)
>         at async @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.$anonfun$client$7(SocketGroupPlatform.scala:62)
>         at map @ com.comcast.ip4s.SocketAddress.resolve(SocketAddress.scala:33)
>         at flatMap @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.connect$1(SocketGroupPlatform.scala:61)
>         at delay @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.$anonfun$client$4(SocketGroupPlatform.scala:58)
>         at onError$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(KeyPool.scala:370)
>         at delay @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.setup$1(SocketGroupPlatform.scala:55)
>         at make @ sharry.common.ThreadFactories$.executorResource(ThreadFactories.scala:42)
>         at make @ sharry.common.ThreadFactories$.executorResource(ThreadFactories.scala:42)

And here the config:
> enabled = true
> id = "aad"
> name = "Azure AD"
> icon = "fab fa-microsoft"
> scope = "openid"
> authorize-url = https://login.microsoftonline.com/6cf7fbb1-1b81-48a0-a1a3-[REMOVED]/oauth2/v2.0/authorize
> token-url = https://login.microsoftonline.com/6cf7fbb1-1b81-48a0-a1a3-[REMOVED]/oauth2/v2.0/token
> user-url = https://graph.microsoft.com/oidc/userinfo
> user-id-key = "email"
> user-email-key = "email"
> client-id = "34ebbf6d-a889-4bf9-920b-[REMOVED]"
> client-secret = "[REMOVED]"

I think there's a loop inside the server.
Nginx is in front for HTTPS and the servername is the same as the base-url parameter.
Also, the server is able to resolve himself.

Any idea ?
Thanks

**Comment by eikek** [comment]
Hi @rosswell98 from the error message it seems that the endpoint (one of the configured IdP ones) is not reachable or otherwise takes too long to respond.

Can you maybe add more logging by adding this to your config:
```
sharry.restserver {
  ...
  logging {
     levels = {
        "sharry.restserver.oauth.CodeFlow" = "Trace"
        "sharry" = "Debug"
      }
   }
}
```

**Comment by rosswell98** [comment]
Hello @eikek,

Thank you, Indeed it seems to be blocked.
We are forced to use a proxy but connections to the IdP doesn't go trough.
However, I set variables in the env file of Sharry :
- http.proxyHost
- http.proxyPort
- https.proxyHost
- https.proxyPort

Theses variables appears in "systemctl status".
The application is considering these variables in the code ?

**Comment by eikek** [comment]
Hi @rosswell98, unfortunately for the IdP requests there is no proxy supported at the moment.

**Comment by rosswell98** [comment]
Hello @eikek !
Thanks, we'll open the web trafic to the IdP.
Do you think it'll be supported in next versions ? 😃

**Comment by eikek** [comment]
Hi @rosswell98 , this is not planned so far :/. I was looking a bit into it yesterday when looking at the issue. Apparently, the library I use to make these requests doesn't support proxies. So it is probably a bigger endeavor than I had first thought.

**Comment by rosswell98** [comment]
Hello @eikek, OK so we need to open web traffic to the IdP.
It works like this, thanks you :)
