### ISSUE TITLE
CORS blocked when uploading a file using Caddy reverse proxy.

### ISSUE THREAD

**Issue by Blizliam** [eikek/sharry#1312]
I was able to get sharry working with no issues using the local IP and port at **10.0.10.21:9090**. This instance is running in a docker compose stack.

Config:

    sharry.restserver {

        base-url = "https://sharry.mydomain.com"

        bind {
            address = "0.0.0.0"
            port = 9090
        }

        webapp {
            initial-page = "share"
        }

        backend {
            auth {
            fixed.enabled = true ## enabled admin:admin access
            }

            jdbc {
            url = "jdbc:postgresql://db:5432/*"
            user = "*"
            password = "*"
            }

            signup {
            mode = "open"
            invite-time = "14 days"
            invite-password = "generate-invite"
            }
        }
    }

My issue is that once I access and try to upload files using Sharry behind a Caddy reverse proxy, I get CORS errors like below in my browser (firefox).
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sharry.mydomain.com:9090/api/v2/sec/upload/JCd9LRJBHYP-kZo6E8eadwe-equZjVYUq1A-8Jn6G7ZqK9i/files/tus/76PNtbgyApS-4qP2sfdQoC2-4auQVJ55pTP-TKovazTZ9fe. (Reason: CORS request did not succeed). Status code: (null).
`

When I first experienced this issue, I also couldn't log in using the proxied address. Adding the entry `sharry.mydomain.com:9090` resolved that issue.

Here is my Caddy configuration for Sharry:

```
sharry.mydomain.com:9090 {
        reverse_proxy 10.0.10.21:9090
}

sharry.mydomain.com {
        reverse_proxy 10.0.10.21:9090
}
```
Here is the exception that occurs in the logs:

```
sharry_app          | 2024.01.29 14:59:35:0000 [io-comp...] [ERROR] sharry.restserver.RestServer.applyOrElse:48 - Error processing request!
sharry_app          | java.io.IOException: Connection reset
sharry_app          |   at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:425)
sharry_app          |   at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:195)
sharry_app          |   at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217)
sharry_app          |   at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306)
sharry_app          |   at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
sharry_app          |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
sharry_app          |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
sharry_app          |   at java.lang.Thread.run(Thread.java:840)
sharry_app          |   at delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.$anonfun$readChunk$1(SocketPlatform.scala:120)
sharry_app          |   at async @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.readChunk(SocketPlatform.scala:114)
sharry_app          |   at flatMap @ fs2.io.net.SocketCompanionPlatform$BufferedReads.$anonfun$read$1(SocketPlatform.scala:82)
sharry_app          |   at delay @ fs2.io.net.SocketCompanionPlatform$BufferedReads.withReadBuffer(SocketPlatform.scala:52)
sharry_app          |   at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
sharry_app          |   at getAndSet @ org.typelevel.keypool.KeyPool$.destroy(KeyPool.scala:120)
sharry_app          |   at deferred @ fs2.concurrent.Channel$.bounded(Channel.scala:150)

```

Any help here would be nice. If there is a configuration I am missing, please let me know. Thank you! ;)

**Comment by eikek** [comment]
Hi @Blizliam ,

I'm not sure what the cause is. If cors is blocking the request, then probably the api goes to a different url then what you have in your address bar? The url in `base-url` and the one in your address bar should be the same.  If you have `https://sharry.mydomain.com` in your config, then you need to use this to connect to sharry (not adding the port, for example). 

The exception is not clear, sadly. It is probably a dropped connection at the other end.

**Comment by Blizliam** [comment]
That is consistent with what I am seeing. To clarify, when this is happening I am only browsing to `https://sharry.mydomain.com` and not specifying the port. The port is included in only those XHR requests coming from `tus.min.js` file as seen in my screenshot. The `sharry-app.js` file is requesting from the expected base-url (and succeeds).

You can see on the far left where the port is either included, or not.

![image](https://github.com/eikek/sharry/assets/35822900/ac900c82-780b-4eb7-907e-12dde9f8b998)

**Comment by eikek** [comment]
Hm, that is strange - the client gets the url from the server config. Can you check what is returned by `/api/v2/open/info/appconfig`? Perhaps some caching problem on the browser?

**Comment by Blizliam** [comment]
(The appconfig gave the expected correct base-url)

Clearing the cache totally resolved the issue. I should've thought to try that.

Thanks for the help and sorry for taking your time!

**Comment by eikek** [comment]
No worries! Good it was just this.
