### ISSUE TITLE
mp4 files are not playing in browser

### ISSUE THREAD

**Issue by albertbern** [eikek/sharry#1328]
mp4 files are not playing in browser

ver 1.13.1

logs:

```
Feb 19 18:53:52   sharry-restserver[815078]: 2024.02.19 18:53:52:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v2/open/share/AmWPnFULrUC-qG6bPXeV1jd-d4qyp6UhrnN-Xar5UudJ4kP/file/9bFpMzPmxG1-eiBsLa56wcE-KcbJMLPXdS2-44NhNjT52x6
Feb 19 18:53:52   sharry-restserver[815078]: 2024.02.19 18:53:52:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 206 Partial Content

```

`- - [19/Feb/2024:18:53:52 +0200] "GET /api/v2/open/share/AmWPnFULrUC-qG6bPXeV1jd-d4qyp6UhrnN-Xar5UudJ4kP/file/9bFpMzPmxG1-eiBsLa56wcE-KcbJMLPXdS2-44NhNjT52x6 HTTP/1.1" 206 135428 "XXXXXX/app/open/AmWPnFULrUC-qG6bPXeV1jd-d4qyp6UhrnN-Xar5UudJ4kP?view=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
`

**Comment by eikek** [comment]
What is happening instead in the browser? Can you see error messages in the browser console? I just tried on my (still 1.13.0) installation and mp4 files are playing fine (firefox).

**Comment by albertbern** [comment]
No errors -  GET Status Code: 206 Partial Content
Chrome - does not play
Edge - does not play
It works only in firefox

**Comment by albertbern** [comment]
Chrome and Edge  - small player window appears and it become inactive in a sec.

Player in Firefox works only by downloading file from the start. Is it possible to have player that can start from any position? 
User mp4 files are huge.

**Comment by eikek** [comment]
I see, thank you for checking. I need to investigate, I could play my files well, but they weren't very big.

**Comment by kqfflo** [comment]
I was about to open a case myself as I seem to have the same issue. 
Maybe this helps a little:
I still need to stick with **1.12.1** . Starting with **1.13.x** videoplayback stopped working. 

Loglevel trace does not reveal any additional details:

`2024.02.27 14:36:45:0006 [io-comp...] [DEBUG] com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.mariadb.jdbc.Connection@5177f61d
2024.02.27 14:36:45:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v2/sec/share/FtE8wuKEfu2-QGV8rZ23o74-z6p89drmGBe-EkjwyGrrpqo/file/2tHUFvk5bJv-amiq9SwKg3m-oMZZxTpLget-DnHfp9AVL5e
2024.02.27 14:36:45:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 206 Partial Content`

Also the dev cnsole does not bring up anything meaningful or error. 

@eikek Can you maybe check and see, if 1.12.1 works for you? (you can use the same database as with 1.13.x - but have a backup)

**Comment by eikek** [comment]
Thanks @kqfflo , this is always very helpful!

**Comment by albertbern** [comment]
Can confirm, 1.12.1 works.
1.13.* are not.

**Comment by eikek** [comment]
Hi, I pushed a fix - it will be in the snapshot releases shortly. If you could perhaps test it and report back, that would be great!

**Comment by kqfflo** [comment]
I can confirm that this fixed the issue. Using 1.14.SNAPSHOT now. 
This fix is highly appreciated - thank you!

**Comment by eikek** [comment]
Thank you @kqfflo for reporting back! I will make a bug-fix release soon.
