### ISSUE TITLE
Sign-in with oauth (via Google) creates accounts even if signup is set to "invite" or "closed"

### ISSUE THREAD

**Issue by bbqf** [eikek/sharry#1344]
Hi, 
I am setting up sharry on my home server and the idea was to enable sign-in via oauth providers, but make it a closed server, so that my friends and relatives will be able to use it, however only the ones that get an invitation from me. Signing in with Google works perfectly, however I cannot limit new users from being created automatically while signing in.

I set up oauth via Google, set the signup to "closed", the login page doesn't display the option to sign-up:
![image](https://github.com/eikek/sharry/assets/18129227/1c0b5556-ab01-4408-ad80-3f16f2f6974c)
So far so good, however if I click the button "via Google", the account gets created automatically. Same happens if signup is set to "invite".

Here's the corresponding log part:
```
2024.03.05 09:03:28:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v2/open/auth/oauth/google
2024.03.05 09:03:28:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 302 Found
2024.03.05 09:03:32:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /sw.js
2024.03.05 09:03:32:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 200 OK
2024.03.05 09:04:18:0000 [io-comp...] [INFO ] sharry.restserver.oauth.CodeFlow.codeToToken:73 - Got token: Some(xxxxxxxx)
2024.03.05 09:04:18:0000 [io-comp...] [INFO ] sharry.restserver.oauth.CodeFlow.resp:100 - Got user id: Some(UserInfo(Ident(xxxxxx@gmail.com),None))
2024.03.05 09:04:18:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v2/open/auth/oauth/google/resume?state=xxxxxx&scope=email+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&prompt=consent
2024.03.05 09:04:18:0002 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 307 Temporary Redirect
2024.03.05 09:04:18:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /app/login?oauth=1
2024.03.05 09:04:18:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 200 OK

```
auth and signup are configured like:
```
        auth {
          fixed.enabled = false ## enabled admin:admin access
          oauth = [
            {
              enabled = true
              id = "google"
              name = "Google"
              icon = "fab fa-google"
              scope = "email"
              authorize-url = "https://accounts.google.com/o/oauth2/auth"
              token-url = "https://oauth2.googleapis.com/token"
              user-url = "https://www.googleapis.com/oauth2/v3/userinfo"
              user-id-key = "email"
              client-id = "xxxxxxxxxxxx"
              client-secret = "yyyyyyyyyyyy"
            }
          ]
        }
        signup {
          mode = "closed"
          invite-time = "7 days"
          invite-password = "zzzzzzzzzzzzzzz"
        }

```

Note 1: There's a discrepancy in the configured scope = "email" and the URL from the logs: ...&scope=email+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&...
Note 2: Exactly same log line shows a URL/scope that's nowhere configured, is it hardcoded??? I mean openid seems to be hardcoded as well, but at least it's kind of standard, whereas userinfo.email is from completely different API, although same OpenID has a scope email that I successfully use. 

Probably it's not the cause of the issue, just looks strange that I configure only email and scope of openid and email is requested.

**Comment by eikek** [comment]
Hi @bbqf 

the signup applies to local accounts only. Although it would be nice, Sharry cannot control who can sign up on Google 😄 (just kidding). There is no extra step between openid and sharry. When using openid, signup and other features are delegated to the identity provider. It's meant for people who set up their own keycloak or authentik etc. when user management goes beyond a few users. Should be probably made more clear in the docs somewhere. I can see the use case, though. But this is currently not possible.

The other notes are interesting. I'm not aware of a hardcoded scope. Perhaps some values from the defaults are slipping through. Could you perhaps test again using a different id than `google` (this id is only used to refer to this config section, it can be anything). It would be helpful if you could send a few more log lines for context.

**Comment by bbqf** [comment]
Hi @eikek,

sorry, an intermediate update: my home server disk got corrupted since I wrote this, so I will test your suggestion when the new one gets in.

Regarding the main question: 
From the sign-in flow (local) it should work similar to 1) Authentication: get the user-id and password supplied via form and check them against local database, if there's a match, then 2) Check if the account is disabled, etc. Sign-up is a completely separate process. From what I hear, OAuth flow, skips both steps and just let the user in (in the signing up the user if non-existent), correct? So why is it not possible to wire OAuth flow to go into step 2 above and let the signup be a separate function? 

I am not an active developer nowadays and never looked at scala anyways, so I wouldn't try to go into the code, however this doesn't feel too complex yet it would close a potential security hole, if anyone tries to use sharry like I described. What do you think?

**Comment by eikek** [comment]
Hi @bbqf oh no, I hope you get everything back working with the new disk!

It is of course possible in general, but it only currently is not :). It requires some work and I don't think it will be so easy. Not conceptually difficult, perhaps, but someone has to go through the code and wire things together. It will also require a new ui step. As I said, the current setup is meant when you host your own identity provider, not using public one. To me it's really not a security whole, a user must chose very deliberately to open their server and apps to the general public (and test before doing so).

I can see the benefit and I'd be fine with this change, but I won't have time for this in the near future.
