### ISSUE TITLE
[Enhancement] Better mobile page

### ISSUE THREAD

**Issue by FuzzyMistborn** [eikek/sharry#136]
This is a great little program and checks virtually all the boxes for me.  My only major gripe is the page doesn't scale well on mobile.  The text is so small that you have to zoom in.  Would be nice if there was a more mobile-friendly version available.  No idea if that's something that's possible and it's not a dealbreaker but would make things much better I think.

**Comment by eikek** [comment]
Yes, you ar so right! It is certainly possible, it's just that I'm not the "web-guy" and ususally shy away from these things :sweat_smile: But I also run into this and think, that it has to be improved. I'll try first if there is a better responsive version possible using tools in the css-framework (semantic-ui).

**Comment by eikek** [comment]
Hi @FuzzyMistborn , so this was just an ordinary bug, because the viewport definition was not  set, so mobile browsers didn't know to zoom in. It is still not perfect, though. If you find any misbehavour, feel free to create issues for them.
