### ISSUE TITLE
Disable new user signup

### ISSUE THREAD

**Issue by norrcomm** [eikek/sharry#1398]
How can I remove the option to disable new user sign up from the home page?

I don't want random persons creating an account on my server.
![nosignup](https://github.com/eikek/sharry/assets/131506872/a8f90a57-7340-4947-b5fd-d56b17c1837f)

**Comment by norrcomm** [comment]
found in documentation

**Comment by eikek** [comment]
Guess this can be closed then. For reference: https://eikek.github.io/sharry/doc/configure#registration-options
