### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by retechp** [eikek/sharry#1403]
How can I make Sharry work with Nginx?

Right now, every time I got to HTTP://www.mydomain.com:9090, it redirects to https://www.mydomain.com

Is there a configuration I can use to create a site within my Nginx config?

**Comment by eikek** [comment]
Sharry is nothing special in this regard, just do as you would with other services. There is an example in the docs here: https://eikek.github.io/sharry/doc/reverseproxy#nginx Maybe this can be a starting point?
