### ISSUE TITLE
Run Sharry as a service

### ISSUE THREAD

**Issue by retechp** [eikek/sharry#1404]
How can I make Sharry run as a service?

At present, Sharry only runs when I leave my console logged in and I manually start the application.

**Comment by eikek** [comment]
This very much depends on your system. There is no standard way. Sharry provides something for NixOS and also Debian I think.

**Comment by retechp** [comment]
> This very much depends on your system. There is no standard way. Sharry provides something for NixOS and also Debian I think.

Thanks and any documentation you can link me to for this?

**Comment by eikek** [comment]
There is this for NixOS: https://eikek.github.io/sharry/doc/nix#sharry-as-a-service-on-nixos
When using Debian, install the deb package and it will install systemd unit files that you can inspect. You can then check the docs of your respective system.
