### ISSUE TITLE
[Feature request] Publish container to Github container registry

### ISSUE THREAD

**Issue by chelming** [eikek/sharry#1405]
It'd be nice to pull a container without having to build it myself 😄 
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by chelming** [comment]
oh. oops! I didn't even think to look there 🙃 I saw the [quickstart](https://eikek.github.io/sharry/doc/quickstart) saying to use the compose file and assumed it was for a build! sorry!

**Comment by eikek** [comment]
No worries! 😄
