### ISSUE TITLE
Authentik SSO FAils | (redirect_uri).

### ISSUE THREAD

**Issue by Ejz9** [eikek/sharry#1450]
This is my config in sharry: 

        "authentik" = {
          enabled = true
          name = "Authentik"
          icon = "fab fa-user"
          scope = "openid"
          authorize-url = "https://mydomain/application/o/authorize/"
          token-url = "https://mydomain/application/o/token/"
          user-url = "https://mydomain/application/o/userinfo/"
          user-id-key = "preferred_username"
          user-email-key = "email"
          client-id = "myID"
          client-secret = "mySecret"
        }
        
In authentik I have setup everything to my awareness, correctly, however I get a redirect URL error:

The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri).

The URL I have set in authentik to have it redirect any user back to is:

share.mydomain.com aka the sharry site

I also am using these both behind NPM plus so I am not sure if this is a cause...

I also saw a previous issue regarding Authentik and followed it but I'm stuck at redirection failing. Where do I need to redirect my Oauth to return to accessing sharry?

**Comment by eikek** [comment]
I'm not sure I understand correctly: which redirect fails, the one from sharry to authentik? Or the redirect back to sharry from authentik? Are there maybe any errors in the logs of authentik (and sharry)?

**Comment by Ejz9** [comment]
Hi, the redirect from authentik back to sharry is where I am having the issue.

Also with authentik setup for portainer and jellyfin currently to and working for them I'm assuming it's on sharry's side.

I looked at some of the logs when doing this yesterday and nothing stood out, I will have to take another look after work today. But the error to me seems where authentik doesn't route back to "sharry.mydomain.com" from its authentication page.

**Comment by eikek** [comment]
Thanks for checking! I'll try to reproduce it on my machine and hopefully can see something.

**Comment by eikek** [comment]
Hi @Ejz9, sorry for the delay. I just tried to reproduce it on my dev setup, but here it works. My 
config is this:

```
"authentik" = {
  enabled = true,
  name = "Authentik",
  icon = "fab fa-openid",
  scope = "",
  authorize-url = "http://localhost:9000/application/o/authorize/",
  token-url = "http://localhost:9000/application/o/token/",
  user-url = "http://localhost:9000/application/o/userinfo/",
  user-id-key = "preferred_username",
  client-id = "<client_id>",
  client-secret = "<client_secret>"
},
```

I assume we have setup authentik differently. I just added an openid provider, set it to confidential and connected a new application for sharry. For the redirect uri in authentik application settings, I set it to `http://localhost:9090/api/v2/open/auth/oauth/authentik/resume`. I think this is all I did differently to the defaults.

**Comment by Ejz9** [comment]
Hi, I tried your config which is not to different from mine but every time it goes to redirect it fails still. I still get:

The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri).

Something I noticed too was if I do not set the link I get rerouted to: https://86.48.9.123/api/v2/open/auth/oauth/authentik/resume or something similar which is not my IP nor have I set anywhere for it to route there. 

Setting the redirect to what you suggested it does not work and in the URL also includes this IP which I still have no idea where its from or why. I think the redirect for sharry isn't matching authentik even when it's properly set. Why? I do not know. Maybe some data had some old entry somewhere.

I am completely unable to use sharry now though as I nuked it, pulled a new image, re-did the config from your website docs which works fine but (strangely duplicates itself multiple times) which also seems to happen between restarts/redeployment of the container. Now I am not even able to access the local ip plus port or even the external FQDN from my reverse proxy though effectively I cannot access the service even though it says it has started on 127.0.0.1:9090. I did not change ports or anything.

I would like to use sharry but I am not sure why these weird events are happening.

**Comment by eikek** [comment]
> Something I noticed too was if I do not set the link I get rerouted to: https://86.48.9.123/api/v2/open/auth/oauth/authentik/resume or something similar which is not my IP nor have I set anywhere for it to route there.

It is always difficult to diagnose these things as it depends so much on the specific setup. If you have something in front, it might be that you need to configure sharry differently. So I can imagine the ip you see (86.48.9.123) is the machine that connects to sharry and since sharry doesn't know the "outside" address, it guesses it from the incoming request and probably finds this ip. That is then used to construct the redirect uri that is send to the IdP. you can change this by setting teh appropriate headers in your reverse proxy or by setting the `base-url` config option (see https://eikek.github.io/sharry/doc/configure#base-url).
