### ISSUE TITLE
[Feature Request] Run as unprivileged user in container

### ISSUE THREAD

**Issue by hlx-a1** [eikek/sharry#1496]
Hi, thanks for developing this software.

Currently, the sharry docker image runs as root. Therefore, if sharry is being run under K8S it is very likely that the process is running as root on the host, which is a Bad Idea™.

In theory this should be as simple as adding the following to `sharry.dockerfile`:
```Dockerfile
RUN addgroup -S user -g 10001 && \
    adduser -SDH user -u 10001 -G user
USER 10001
```

**Comment by eikek** [comment]
Hi @hlx-a1 thanks for the suggestion, I totally agree. If you have the time and energy, you can do a PR with the changes you think are necessary. 👍🏼 🙏🏼

**Comment by kastl-ars** [comment]
I created a PR using the dockerfile I used to locally build and test this. It worked in my tests!
