### ISSUE TITLE
Editing "Validity Time" doesn't modify "Published until" date

### ISSUE THREAD

**Issue by Pafzedog** [eikek/sharry#167]
Hi,

When I edit "Validity Time" of a share, the date in the field "Published until" is not changed.
I have to unpublish and publish again the share for this, I  don't know if this is a normal behavior but others settings are applied on the fly but this one not.

**Comment by eikek** [comment]
Yes, this is currently intended. Of course, it is debatable whether this is reasonable. My thoughts back then were that something like changing the lifetime of a public link should be explicitly requested by the user. I can see that one would expect it to be immediately applied to the publish-until time. There is no other reason for changing the validity time anyways, so I'll change this.
