### ISSUE TITLE
[Enhancement] Add a copy link button

### ISSUE THREAD

**Issue by Pafzedog** [eikek/sharry#191]
Hello,

Adding a "Copy link" button next to "Send e-mail" might be a good idea.
Here are some arguments ;)

- The link created by Sharry is not clickable.

- Some users could use an email client instead of Sharry's "send email" button.

- Some administrators may not be able to install a smtp connector on their server.

![2020-07-01 16_17_19-eikek_sharry_ Sharry is a self-hosted file sharing web application](https://user-images.githubusercontent.com/8932092/86255715-be0aa780-bbb7-11ea-8da7-a836e5b57b8e.png)

What do you think ?

**Comment by eikek** [comment]
Yes, sure! This is very convenient. Would you make the link clickable? I thought this might lead the user to really click on it, where it is not for this purpose actually… but I'm not sure.

**Comment by Pafzedog** [comment]
You're right, I wouldn't make the link clickable but just pickable  maybe, in fact, adding a copy button should be more efficient.

**Comment by eikek** [comment]
Hi @Pafzedog , I'm sorry to bother you again…  could you maybe give me the French translation for the "Copy Link" button? Google translate says it is "Copier le lien" – but maybe it's not :-) No need to hurry, though!

**Comment by Pafzedog** [comment]
Hello @eikek, don't worry, I'm happy to help :)
you'r right ! "Copier le lien" is perfect !

**Comment by Pafzedog** [comment]
Hey @eikek !
Will you make a release with these awesome enhancements ? :p

**Comment by eikek** [comment]
Of, course :-) My plan is to do a 1.4.0 release with the current things. I'm away for the weekend, but it happens next week :-)
