### ISSUE TITLE
Translating date

### ISSUE THREAD

**Issue by Pafzedog** [eikek/sharry#192]
Hi,

it would be nice if date (Created, published on, etc ...)  could be translated too.

thanks

**Comment by eikek** [comment]
Ah yes, you're right. I totally forgot about these dates.

**Comment by eikek** [comment]
Hi @Pafzedog , so I just had  some time to look into this. Fortunately one library in use, [ryannhg/date-format](https://github.com/ryannhg/date-format), already had translations for French, which I took. But this only applies to the date components, like month name and weekday name. The date pattern is left as is, because (sadly) I don't know French…. So … could you maybe have a look at this? It is in `Messages/DateFormat.elm`, the [format](https://github.com/eikek/sharry/blob/master/modules/webapp/src/main/elm/Messages/DateFormat.elm#L88) part. This defines how the date-time string looks like.

**Comment by Pafzedog** [comment]
ok, for french language we have to put day name before month name, I think also that comma between month and year is not needed and replacing comma after day of week by a dot is more "in the rules" of the language for an abbreviation.

Something like this

```
{ format =
        [ DateFormat.dayOfWeekNameAbbreviated
        , DateFormat.text ". "
        , DateFormat.dayOfMonthSuffix
        , DateFormat.text " "
        , DateFormat.monthNameFull
        , DateFormat.text " "
        , DateFormat.yearNumber
        , DateFormat.text ", "
        , DateFormat.hourMilitaryNumber
        , DateFormat.text ":"
        , DateFormat.minuteFixed
        ]
    , lang = french
    }
```

**Comment by eikek** [comment]
Thank you! It would look like this:
![Selection_023](https://user-images.githubusercontent.com/701128/86296212-90921e00-bbf8-11ea-80f3-a0be4c6b78cf.png)

Does this look ok?

**Comment by Pafzedog** [comment]
After a better look to french translation in this library, I think I don't agree with the author about dayOfMonthSuffix.
In french, only the first day of the month need the suffix "er", all the others are just left as it.
It seems that the dev add "e" as suffix for all the other days.
I opened an [issue](https://github.com/ryannhg/date-format/issues/30#issue-649356166)

**Comment by Pafzedog** [comment]
> Thank you! It would look like this:
> ![Selection_023](https://user-images.githubusercontent.com/701128/86296212-90921e00-bbf8-11ea-80f3-a0be4c6b78cf.png)
> 
> Does this look ok?

It is far better than before but this "e" suffix look weird.
PS: sorry but we wrote at the same time ;)

**Comment by eikek** [comment]
Ah ok, thanks! Good is, we can just change it in sharry. 

So, if I understand correctly, it should read like this:

``` elm
toFrenchOrdinalSuffix : Int -> String
toFrenchOrdinalSuffix n =
    if n == 1 then
        "er"

    else
        ""
```
?

Do you maybe want to do this change? (so I don't take credit that is not mine) But I can change this, of course, if you want.

**Comment by Pafzedog** [comment]
It's perfect like that.
If you can make the change, I don't really care about fatherhood and, to tell you the truth, I think it would take me hours to get my git repository up and running again.  XD

**Comment by eikek** [comment]
Sure :-) Thank you a lot!
