### ISSUE TITLE
Description text is lost when switching view

### ISSUE THREAD

**Issue by Pafzedog** [eikek/sharry#195]
Hello,

When you type a description text without saving it and then change the view to "split" or "preview", the text is lost.
I don't know if this is normal behavior, but it's quite surprising the first time.

**Comment by eikek** [comment]
Oh no, this is a bug! I have to look into it. It is "only" when editing an existing share, right? I couldn't reproduce it when you create a new share. Thank you for reporting this!

**Comment by Pafzedog** [comment]
yes, you're right, It's only when editing an existing share.
