### ISSUE TITLE
make the download button more visible

### ISSUE THREAD

**Issue by Pafzedog** [eikek/sharry#196]
Hi,
I find that the download button is not visible enough, it's far away from the file's title on large screens et very small too.
I'm afraid that end users will be looking for it, it should be more visible by higlighting it by color or intuitive text or something else.

![2020-07-03 15_22_40-Window](https://user-images.githubusercontent.com/8932092/86476595-220fa600-bd47-11ea-8192-a3514dd5487b.png)

What do you think ?

**Comment by eikek** [comment]
Yes, I agree! I'm really not good with ui things…. Thanks for making this aware. Here are some thoughts: It could be blue and maybe also contain a text label, like "Download"? Or maybe move the button to the left side, right next to the name? The name could also be clickable and initiate the download.

**Comment by Pafzedog** [comment]
I think changing the color is a first good step.
Adding a text label will be nice but how to make it fit in the same space, I'm afraid it breaks your design ? same about moving it to the left ...
The name should definitively be clickable, it's really an intuitive way to initiate the download imho.

**Comment by eikek** [comment]
Yes, I think these are good ideas. Thank you! If the button has some color and the name is clickable, this should be a good improvement in finding the download link. I'll change this and make a release with this included.

**Comment by eikek** [comment]
It would look like this now:
![Selection_026](https://user-images.githubusercontent.com/701128/86820967-13e4c100-c08a-11ea-9892-63253b1f38b7.png)
![Selection_027](https://user-images.githubusercontent.com/701128/86820975-16471b00-c08a-11ea-84e0-0e1b686952c6.png)
