### ISSUE TITLE
Actual configuration displayed in the manual tab

### ISSUE THREAD

**Issue by maxanier** [eikek/sharry#21]
I have double checked, my /#manual/configuration.md displays the actual configuration at the bottom as the "Default configuration".

Regarding my setup:
I build my self a small docker image and I can reproduce the configuration issue when passing the config via env variables

~~The config displayed in the manual seems to be outdated sometimes (displays older configurations values I already changed to something else), maybe it is cached in the browser~~
Yes it is cached in the browser and sharry returns 304 not modified (even though it is modified)

**Comment by maxanier** [comment]
Try to disable caching (In Firefox there is a checkbox in the developer console-> network)
Maybe it just displays an old configuration for you.

Another question: How does passing the configuration file work, I have setup a config file at /opt/sharry/config.conf and start sharry with `/bin/bash -c /opt/sharry/modules/server/target/scala-2.12/sharry-server-0.3.0.jar.sh /opt/sharry/config.conf` but it does not seem to load the configuration from the file.

Passing environment variables works fine

**Comment by eikek** [comment]
Thanks for reporting! Yes, environment variables and system properties show up in the manual, which is really bad. Values from the config file however, don't (at least). I'll fix that as soon as I find time!

Regarding starting: the config file is simply a parameter to the program, almost as in your example. If you use `bash -c` you must pass one argument to `-c`, so the whole command–including arguments–should be inside quotes, like
```
bash -c "/path/to/sharry.jar.sh /path/to/config"
```
I'm using this, too, and it works for me.

**Comment by eikek** [comment]
Regarding the caching of the manual files: they shouldn't change actually. So once this is fixed, caching them should be ok.
