### ISSUE TITLE
File Previews are often broken

### ISSUE THREAD

**Issue by pluisenbol** [eikek/sharry#216]
With .txt files the background is invisible https://prnt.sc/tws186
With .html files the background is also invisible https://prnt.sc/tws5sj
The video file preview box does not take the same height as the played video file https://prnt.sc/tws379
and for some reason you can scroll a bit into nothing https://prnt.sc/tws3e0

**Comment by eikek** [comment]
Thank you for reporting. Tbh, I didn't put much effort in the previewer, it was a "nice to have" :). Most things should be fixable by some css fiddling.
