### ISSUE TITLE
error sending mails with sharing links

### ISSUE THREAD

**Issue by fstcapb** [eikek/sharry#230]
I use sharry 1.4.0 deb package on ubuntu 16.04 with postresql 9.5

When I try to send "share this link" mails from section shares or section aliases, it comes to a code 500 error. 

The log says: 
Aug 31 17:09:29 SHARRY sharry-restserver[1476]: 2020-08-31 17:09:29,578 [ioapp-compute-8] #033[1;31mERROR#033[0;39m #033[36ms.s.d.DoobieMeta#033[0;39m - SQL Failure: ProcessingFailure(SELECT  email  FROM  account_  WHERE  id  = ? ,List(Ident(975QvCGMD1p-vJqb9THM32x-pq3JcC1iap6-z34TCyvTCrR)),1123001 nanoseconds,830065 nanoseconds,org.postgresql.util.PSQLException: The column index is out of range: 2, number of columns: 1.)

Other mail notifications e.g. for incoming shared files work.

Thanks for helping me to fix that.

**Comment by eikek** [comment]
Hello @fstcapb , oh sorry this is a bug! The code wants to read two things but the query returns only one. I'll fix that and make a release; but this could take some days (due to missing time). Unfortunately, I don't have an idea for a workaround.

**Comment by eikek** [comment]
Fixed via #238

**Comment by fstcapb** [comment]
Great, thank you very much for the fix and the helpful software.
