### ISSUE TITLE
Where does Sharry store the uploaded files?

### ISSUE THREAD

**Issue by xge** [eikek/sharry#250]
Hi,
thanks for the great work on Sharry, I'm really loving it so far.

I was wondering where the uploaded files are stored, since I am a little short on disk space and was thinking about moving the uploads to a different disk. Is there a way to config this and what's the default value?

Thanks!

**Comment by eikek** [comment]
Hi @xge ,

thank you for your kind words, I'm happy you like it! Sharry stores the files in the database as chunks of blobs. So it would involve moving the database directory to another disk. The default value is a H2 database, which is an "in-process" db that stores everything on the filesystem. So if using H2, it should be enough to change the JDBC url to point to another location, some examples are [here](https://eikek.github.io/sharry/doc/configure#examples).  The default is in the global tmpdir, i.e. the URL is `"jdbc:h2://"${java.io.tmpdir}"/sharry-demo.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"`. For H2 you need to first shut down sharry, move the file and then start sharry with the new location (while keeping the parameters).

**Comment by xge** [comment]
Thank you for the explanation. Currently I am using the MariaDB backend, so I will look into moving to H2 and then changing the location. Thanks for your help!

**Comment by eikek** [comment]
When using MariaDB, you also have the option to change the `datadir` in `/etc/my.cnf` (here is some [docs](https://mariadb.com/kb/en/server-system-variables/#datadir) on this). H2 is great, but since it is in-process MariaDB is more performant especially for larger setups.
