### ISSUE TITLE
Allow setting a custom url identifier

### ISSUE THREAD

**Issue by maxanier** [eikek/sharry#26]
Allow editing an alias to be reachable under "https://domain/#a=custom_name" instead of "https://domain/#a=OTNzD9cvFAG7aUK8gUo1n".

Would be a nice to have feature, but should only be considered if it is not too time consuming to implement as one could always just use a link shortener (self hosted of course :D ) as a workaround.

**Comment by eikek** [comment]
@maxanier thank you for the feedback! Yeah, I agree that is a reasonable feature request. It shouldn't be very expensive to implement (I think).

**Comment by eikek** [comment]
@maxanier I implemented it and it lives now on the master branch. I was thinking about it more during implementation and I'm not sure if it is such a good feature, as a user can now put in quite simple ids that are easily guessable. After all this page allows to upload much data to your server. Maybe it should be hidden behind a config flag…. But maybe it's just fine to leave it like it is now :)

**Comment by maxanier** [comment]
Great!
I will update my instance as soon as I find time.
In my use case I am the only registered user, so I can make sure that the used ID's are reasonably hard to guess. 

Even if someone random is able to upload something it should not be that big a deal as they can't download it themselves (so no sharing of illegal content) and I can always delete things again. Only concern might be security, not sure if it is possible to upload malicious content to attack the server (ok, probably something like this is always possible, the real question is how difficult :D).
 
For larger deployments this might be more of a problem I guess

**Comment by eikek** [comment]
Yes, that's true – it's only an issue for langer deployments. So it's not a pressing thing to solve right now :-) Can think about it if it ever comes up again. Thanks for your feedback!
