### ISSUE TITLE
Newly "created" Fixed admin account is not administrator

### ISSUE THREAD

**Issue by gboudreau** [eikek/sharry#279]
I edited `sharry.conf` (to enable Fixed & Internal auth, amongst other things), didn't specify a database (a new H2 db file was created), and started Sharry (using Docker).
The admin/admin account I was able to login with did not have the admin flag (I verified in the `account_` table, in the H2 DB). This prevented me from being able to see the `Accounts` menu item, and thus create a new admin (internal) user.
I had to manually edit `account_.admin` to `TRUE` in the H2 DB.

Maybe because some incompatibility between Fixed and Internal auth..? Maybe one should not enable both together, or the admin user created in the Internal DB won't have the admin flag?

**Comment by eikek** [comment]
Thank you for reporting! I look into it. Both auth mechanism should work next to each other without problems. The "fixed" one usually comes first (can be configured).

**Comment by bckmnn** [comment]
I can confirm this behaviour. I also set up sharry via docker. I would not see the Invite-Generation menu when logging in as admin:admin. After connecting to the database and toggeling the flag there it worked.
