### ISSUE TITLE
mail address as login name might not be case sensitive

### ISSUE THREAD

**Issue by fstcapb** [eikek/sharry#300]
We use mail addresses as login names with external authenticator (command) and realised that the user names are case-sensitive.
So the login with test.user@domain.com is another account than Test.User@domain.com and Test.User@ is not able to access the data of test.user and vice versa.
Maybe this does not only happen with command login and you like to change something about that.

**Comment by eikek** [comment]
Thank you, I don't think that it makes sense to have case-sensitive login names. I'm going to change it to make account names case-insensitive.
