### ISSUE TITLE
Oauth login causes 500, which is fixed on reloading

### ISSUE THREAD

**Issue by Luca-Castelnuovo** [eikek/sharry#306]
## Video
https://gofile.io/d/Z2T1i3

## Logs
<img width="1024" alt="Screenshot 2020-11-23 at 14 41 28" src="https://user-images.githubusercontent.com/26206253/99968920-137b6700-2d9a-11eb-9884-0a593f0369d4.png">

**Comment by eikek** [comment]
Thank you for reporting! I'll take a look. Seems that it tries to add the user again, although it already exists.

**Comment by eikek** [comment]
Hi again, I just tried to reproduce using github as auth provider. I can't reproduce it :( The error in the logs is misleading – it is not an error, I have to fix this message. The code only tries to insert and if this fails, it's fine,but the sql failure is logged as error which is wrong. 

What auth provider are you using? Does this happen with all browsers?

**Comment by Luca-Castelnuovo** [comment]
I'm using a custom OAuth provider, I can share my settings. This error occurs on Chrome, I will try safari.

**Comment by Luca-Castelnuovo** [comment]
The error doesn't occur on Safari. It also doesn't happen in Chrome "Guest Mode", maybe ublock origin or something else has a weird interation.
