### ISSUE TITLE
favicon override

### ISSUE THREAD

**Issue by avsdev-cw** [eikek/sharry#309]
Great simple project which really suits the need for a simple file-drop service!

My only issue is that the favicon seems to be hard coded and not configurable which is a shame, unless I have missed something?

(note: I ended up hard-configuring some nginx locations to intercept and redirect the favicon files)

**Comment by eikek** [comment]
It is hardcoded currently, yes. Changing it is not very simple, because a favicon is today not just one file, but many for different devices etc. Maybe it then makes sense to specify the complete template ([this](https://github.com/eikek/sharry/blob/master/modules/restserver/src/main/templates/index.html))? Then nginx can be configured to serve some directory containing all the icons and manifest.json etc and the template can be changed to point to that url?

**Comment by madindehead** [comment]
> Great simple project which really suits the need for a simple file-drop service!
> 
> My only issue is that the favicon seems to be hard coded and not configurable which is a shame, unless I have missed something?
> 
> (note: I ended up hard-configuring some nginx locations to intercept and redirect the favicon files)

Is it possible for you to share how you set that up? Thanks.

**Comment by avsdev-cw** [comment]
> It is hardcoded currently, yes. Changing it is not very simple, because a favicon is today not just one file, but many for different devices etc. Maybe it then makes sense to specify the complete template ([this](https://github.com/eikek/sharry/blob/master/modules/restserver/src/main/templates/index.html))? Then nginx can be configured to serve some directory containing all the icons and manifest.json etc and the template can be changed to point to that url?

That could work, or a template for the favicon block which could be a file replacement and not require any special configuration of nginx/apache?



> > Great simple project which really suits the need for a simple file-drop service!
> > My only issue is that the favicon seems to be hard coded and not configurable which is a shame, unless I have missed something?
> > (note: I ended up hard-configuring some nginx locations to intercept and redirect the favicon files)
> 
> Is it possible for you to share how you set that up? Thanks.

Sure - create your list of favicons (I often use https://realfavicongenerator.net/) and place them in a useful directory (i.e. /var/www/favicon or /srv/sharry/favicon) then add the following to nginx before your `location / {` block
```
    location /app/assets/sharry-webapp/1.5.0/favicon/ {
        alias /var/www/favicon/;
	try_files $uri =404;
    }
```

**Comment by madindehead** [comment]
> 

This is great - thank you. 

I use the Docker image, so I think I need to map the volume across? Then it will work from there.

**Comment by eikek** [comment]
> > It is hardcoded currently, yes. Changing it is not very simple, because a favicon is today not just one file, but many for different devices etc. Maybe it then makes sense to specify the complete template ([this](https://github.com/eikek/sharry/blob/master/modules/restserver/src/main/templates/index.html))? Then nginx can be configured to serve some directory containing all the icons and manifest.json etc and the template can be changed to point to that url?
> 
> That could work, or a template for the favicon block which could be a file replacement and not require any special configuration of nginx/apache?

You mean to specify a file in the config file that is included into the html head section? Sounds good, should be doable without a lot of effort

**Comment by madindehead** [comment]
> > > It is hardcoded currently, yes. Changing it is not very simple, because a favicon is today not just one file, but many for different devices etc. Maybe it then makes sense to specify the complete template ([this](https://github.com/eikek/sharry/blob/master/modules/restserver/src/main/templates/index.html))? Then nginx can be configured to serve some directory containing all the icons and manifest.json etc and the template can be changed to point to that url?
> > 
> > 
> > That could work, or a template for the favicon block which could be a file replacement and not require any special configuration of nginx/apache?
> 
> You mean to specify a file in the config file that is included into the html head section? Sounds good, should be doable without a lot of effort

I was wondering if there was any progress/timeframe on this? Thanks.

**Comment by eikek** [comment]
> I was wondering if there was any progress/timeframe on this? Thanks.

Sorry, no there is nothing like this. I might get to it this year, but it's not for sure, of course.
