### ISSUE TITLE
/app/uploads as homepage

### ISSUE THREAD

**Issue by Luca-Castelnuovo** [eikek/sharry#313]
Could /app/uploads be the starting home page?

**Comment by eikek** [comment]
Yeah, that's a good idea.

**Comment by Luca-Castelnuovo** [comment]
When do you think you can implement this feature?

**Comment by eikek** [comment]
My current plan is to hopefully be able to work on this (and the two other minor issues) in the next weeks, so I can create a 1.6.0 release for early January. It shouldn't be much work, but finding enough time is currently difficult. No guarantees though…. but these are my thoughts today on this :-)

**Comment by Luca-Castelnuovo** [comment]
Ah okay. Be well and happy holidays. No rush, just looking through my issues and seeing this.

**Comment by eikek** [comment]
Hi @Luca-Castelnuovo – you can now set the initial page in the config file. Have a look at `sharry.restserver.webapp.initial-page`. This can now hold one of three values: `home` (default), `uploads` and `share`.
