### ISSUE TITLE
Header parsing error with Google Chrome client

### ISSUE THREAD

**Issue by spascou** [eikek/sharry#35]
There is an issue in parsing request headers made by, at least, Google Chrome 63.0.3239.132

Error is:
`class java.lang.Throwable:Decoding of the request header failed: Headers/Cookie: Expected value with optional parameter, got none`

Indeed, Chrome uses the following headers: 
```
GET / HTTP/1.1
Host: REDACTED
Connection: keep-alive
Cache-Control: max-age=0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie:
```

Note the `Cookie` header without a value, upon which the parser throws an error.

This incomplete header is not present in Firefox or Safari, and the error is not present either.

**Comment by eikek** [comment]
Thank you for reporting! This is really unfortunate; also related to #34. My chromium version is 63.0.3239.108 – there it still works :). I'll first try with newer versions of the http library I'm using, otherwise I can report it there.

**Comment by eikek** [comment]
As suggested here https://gitter.im/fs2-http/Lobby?at=5a608f861dcb91f17766a50c, a custom codec impl is necessary that ignores empty header values.
