### ISSUE TITLE
delete user account

### ISSUE THREAD

**Issue by Tigrecito** [eikek/sharry#360]
Hi,

first of all: great product.. I really like it. pretty simple to setup and does what it should ;-) 
Just one thing I came across: 

how can I delete a user account? I saw, I can disable a user - but delete? didn´t find any way..

thanks in advance

**Comment by eikek** [comment]
Hi and thanks:)

do you mean a user of a collective or the complete account? The former is possible (goto collective profile -> users -> delete), the latter not currently.
