### ISSUE TITLE
Keyboard button ENTER not working when entering password

### ISSUE THREAD

**Issue by shadowking001** [eikek/sharry#381]
Hello,

First, let me thank you for this awesome app, I use it daily on my VPS to share files with friends.
And they use it in the same other way. So basically we don't need to use WeTransfer or any soft of this kind anymore.

It may be stupid, but when I share a password-protected file, a user has to click submit to validate, pressing ENTER does not work.
Not really a bug, maybe an enhancement ? I don't have the least idea of work it takes, so basically don't bother if it's a pain in the *ss to implement such feature.

Thanks again.

**Comment by eikek** [comment]
Hi @shadowking001 thank you! I hardly use passwords, so I never realized this. Thanks for reporting! I don't think that this is going to be much work. Classifying these things is sometings difficult. I think I'll classify it as bug – when in doubt, for the user ;-).

**Comment by eikek** [comment]
I'm sorry this took so long! I wanted to have a release by now, but time is a bit tough recently. Will become better!
