### ISSUE TITLE
I need some help......

### ISSUE THREAD

**Issue by Jupiterss** [eikek/sharry#41]
I'm a newbie to Linux field so i don't really understand what i did wrong as i followed the instruction carefully.
![qq 20180406223741](https://user-images.githubusercontent.com/8213282/38427230-43101b14-39eb-11e8-8fda-7eff5b771c44.png)

**Comment by eikek** [comment]
Sorry for the late reply. That looks quite strange to me. It seems that sbt killed itself. What version of sbt did you run (run `sbt about`)? And what version of Java (run `java -version`)? It also seems that you are running this as the `root` user. Try a different normal one.

**Comment by eikek** [comment]
@Jupiterss if nothing helps, you could try one of the builds at the [release page](https://github.com/eikek/sharry/releases). They contain the files that would come out from `sbt make`.

**Comment by Jupiterss** [comment]
@eikek  Thank you for your kindness, sir^^.
 I'll give another shot in the near future ^^.
