### ISSUE TITLE
Invalid header value

### ISSUE THREAD

**Issue by llann** [eikek/sharry#43]
I got this error recently on Chrome Version 73.0.3683.103 (Official Build) (64-bit)

First time I got this, in the past it was working well.

`class java.lang.Throwable:Decoding of the request header failed: Headers: Invalid header value for accept`

Maybe linked to #35

**Comment by eikek** [comment]
Hello @llann ,

thanks for reporting! This is unfortunate. It is probably related to Spinoco/protocol/issues/56. I'll see if I can further ignore invalid parsed headers to avoid future issues … .
