### ISSUE TITLE
Cleanup job does not appear to run

### ISSUE THREAD

**Issue by Stamper-repo** [eikek/sharry#441]
Hello!

Sharry version: 1.7.1

Thank you for making sharry. The authentication model of signing up to create shares but allowing anyone with a link (and a password) to download it is exactly what I am looking for.

In my evaluation of the software I tried to enable the cleanup job to delete expired shares but it does not appear to run.

sharry.conf
```
sharry.restserver {

  base-url = "http://localhost:9090"

  bind {
    address = "0.0.0.0"
    port = 9090
  }

  backend {
    auth {
      fixed.enabled = true ## enabled admin:admin access
    }

    jdbc {
      url = "jdbc:postgresql://db:5432/dbname"
      user = "dbuser"
      password = "dbpass"
    }

    signup {
      mode = "open"
      invite-time = "14 days"
      invite-password = "generate-invite"
    }
  }
  cleanup {
      # Whether to enable the upload cleanup job that periodically
      # removes invalid uploads
      enabled = true

      # The interval for the cleanup job
      interval = 2 minutes

      # Age of invalid uploads to get collected by cleanup job
      invalid-age = 7 days
   }
}
```

I created the container using the docker-compose file.

I can see in the logging that the cleanup job is enabled: `sharry        | [ioapp-compute-1] 2021-05-12 21:34:28,738 INFO sharry.backend.job.PeriodicCleanup - Periodic cleanup job active`

However, I do not see any lines e.g `Running periodic tasks` or `Cleanup expired shares...` within 10 minutes of executing as defined here: https://github.com/eikek/sharry/blob/master/modules/backend/src/main/scala/sharry/backend/job/PeriodicCleanup.scala

Curious to hear if I am not using the software correctly or this is a bug! Thank you in advance.

**Comment by eikek** [comment]
Hi @Stamper-repo thank you!

I think the issue might be that your cleanup config is outside the `backend` section. The `cleanup` must be moved inside `backend`, for example next to `signup`. The cleanup is by default active, that's why the message appears on start. But the interval is set to 14 days by default, so 10min is not enough :). I hope that fixes it, if not, it's a bug.

**Comment by Stamper-repo** [comment]
@eikek Thank you for the tip. This indeed solves the issue! I can confirm that expired, published shares are now removed considering the invalid age & the interval of the cleanup job.
