### ISSUE TITLE
[Proposal] Clarify documentation & logging of cleanup job

### ISSUE THREAD

**Issue by Stamper-repo** [eikek/sharry#444]
Hello!

Currently the cleanup job section of the documented config is described using terms e.g. 'invalid upload'. This threw me off initially as I thought it had to do with partially uploaded files that need to cleanup. Looking in the code, I deduced that the cleanup job actually does the following:

- Expired, published shares and their files are removed once the expiration datetime is older than `invalid-age`.
- Expired invites are removed based on the `invite-time` from the signup block.
- Orphaned files are removed (but this should not happen).

I would propose to clarify the documentation with what the cleanup job entails.

Also, I think it might be worthwhile to include log lines stating the following:

- At boot, log the interval & invalid age of the cleanup job as received from config on INFO
- Log at least the name of the share and the user it belonged to on removal on INFO

This allows a sysadmin to confirm if the correct settings are applied and to see what is removed when in case of issues without having to enable debug.

Curious to hear what you think of the proposal! If approved, I will create a PR with the proposed changes.

Thanks in advance!

**Comment by eikek** [comment]
Hi! yes this sounds all very reasonable. You are correct in all the points. Orphaned files should not happen, actually. It might be nice to have, if one changes the database outside of sharry. I can see how "invalid upload" is a really unfortunate name here. I'm very happy for a PR! Thank you!

**Comment by Stamper-repo** [comment]
It was fun getting back into Scala and SQL join queries. Here we are: https://github.com/eikek/sharry/pull/453

**Comment by Stamper-repo** [comment]
Merged
