### ISSUE TITLE
sharry 0.6.0 cannot create accounts

### ISSUE THREAD

**Issue by orangelynx** [eikek/sharry#46]
Hi,

I just installed a fresh debian 10 vm with zulu openjdk8-jre. Downloaded and ran sharry 0.6.0 with enabled admin account. When trying to create a new user (which btw is a bit confusing at first, that you have to enter the name for the new account in the search field), i get this error:

Some error occured at the server without giving specific error message: { code = 405, message = "Method Not Allowed" }

any idea what might be causing this? Nothing in the console output either...

EDIT1: Same behaviour with postgresql
EDIT2: sudo doesn't help either (not that it should)

**Comment by eikek** [comment]
Hi, this seems strange. This error is coming from the underlying http lib. This could be caused by a request that doesn't match any of the defined routes. Could you share your config? Or the all console output etc (even if there is not much to read…).

**Comment by orangelynx** [comment]
A nights sleep works wonders... I forgot that I need to set baseurl to something different than localhost even when accessing on the same LAN. I could probably have easily debugged this using the Firefox Network Monitor or something.

**Comment by eikek** [comment]
Great that it is resolved.

Regarding the new user: I totally agrree that it is confusing! This should be improved at some point. Hopefully one doesn't create users so often.
