### ISSUE TITLE
Download as zip causes 100% cpu load.

### ISSUE THREAD

**Issue by orangelynx** [eikek/sharry#47]
Hi,

I'm now successfully running the precompiled sharry binaries in a openjdk8 based docker container. Eventhough session management is still a bit wonky, everything works fine otherwise.

What doesn't work however is the "download as zip" option, which just causes CPU load to spike and stall the application. This doesn't look like a normal dependency issue, so maybe a bug?

**Comment by eikek** [comment]
Yes, that is a bug. Does it happen with all files or "only" with larger/many? I'm not sure when I'll have time to look at this. So I'm thinking about to disable the feature until it can be fixed. That's quite sad, but at least users won't kill the application :)

**Comment by orangelynx** [comment]
So far it happens even with two small pdfs, so i guess it's a universal issue.

**Comment by eikek** [comment]
Ok, thanks; I think I had some luck with small files. But it's not really working anymore, so I'm going to make a release without that feature.

**Comment by eikek** [comment]
There is a 0.6.1 release now without the "download as zip" feature.
