### ISSUE TITLE
[HELP] Pages editing

### ISSUE THREAD

**Issue by DorimeDoge** [eikek/sharry#505]
Hello again :D,

I need some help with pages editing, I cant find where I can add some text to login page, like in signup page there is big "Sign Up" text and I want it to be same in login page, big text "Log In". Can you please tell me where I should edit to get that text? :)

Thanks again!

**Comment by eikek** [comment]
If not forgotten, these strings are all below `Messages/` in the elm source root. You might find [this link](https://github.com/eikek/sharry/wiki/Translation) helpful. The strings for the login page specifically are [here](https://github.com/eikek/sharry/blob/master/modules/webapp/src/main/elm/Messages/LoginPage.elm). The view itself is in `Page/Login/View.elm`.

For these things, I recommend to get familiar with tools like [ag](https://github.com/ggreer/the_silver_searcher) or [ripgrep](https://github.com/BurntSushi/ripgrep), which can scan the whole source tree for strings *really* fast. Example:
``` fish
❯ ag "Sign up"
modules/webapp/src/main/elm/Messages/LoginPage.elm
36:    , signupLink = "Sign up!"

modules/webapp/src/main/elm/Messages/RegisterPage.elm
27:    { signup = "Sign up"
```

**Comment by DorimeDoge** [comment]
Hello,

Oh yes, these tools would help a lot (even with other projects), but which one you would recommend me use for Linux/Ubuntu?

Thanks!

**Comment by DorimeDoge** [comment]
And about page editing, you have to add some lines in Login/view.elm right?

Thanks!

**Comment by eikek** [comment]
> And about page editing, you have to add some lines in Login/view.elm right?

It depends. If you just want to add something for yourself, you can edit the `View.elm`. If you only want to change "sign up", then I would change it in the Messages.elm file. Check the wiki page I linked above, there is information on how to start the app and where to edit things. It should be straightforward to adopt to your case, I think.


> which one you would recommend me use for Linux/Ubuntu? As I understand you are using **ag**?

I'm using `ag` because I've been using it for a long time now. But it doesn't matter at the end, both are great. ripgrep is newer and faster it seems.

**Comment by DorimeDoge** [comment]
Hello,

I tried to make it, but cant make it work. Could you help me? :)

<img width="925" alt="Screenshot from 2021-07-21 20-49-14" src="https://user-images.githubusercontent.com/57041295/126536460-f1755f50-8d06-4f45-97de-fb2c903a8591.png">

Thanks!

**Comment by DorimeDoge** [comment]
Hello,

**Comment by eikek** [comment]
Hi, I'm not sure what you are asking? What doesn't work? What is the error message? etc :-)

**Comment by DorimeDoge** [comment]
Hello,

So what I want to make is to put big "Login" text in login page:

![image](https://user-images.githubusercontent.com/57041295/126670921-60bbcf0b-b62f-4509-a866-2c246de0ac6d.png)

Like in sign up page:

![image](https://user-images.githubusercontent.com/57041295/126671011-f2600621-ed2c-4afa-b73d-209d824994d8.png)

But, I cant make it work. I added variable (or I dont know how you call them I am only JavaScript person :D):

<img width="927" alt="Screenshot from 2021-07-22 18-57-04" src="https://user-images.githubusercontent.com/57041295/126671204-767d1a13-6b3d-422e-bdee-559b8a11178d.png">

And this is code how I tried to add that text:

https://pastebin.com/t0tEFsFH

Didnt got any errors, just compiled successfully, but still cant see it.

Thanks!

**Comment by eikek** [comment]
Ah ok, I think I just understood now what you are trying to do…. I didn't realize that the red boxes were diffs.

The login page doesn't have this text yet, so you did it right and added it in there (copying the classes etc from the register page). It looks good from here. How did you build it then - did you build the zip files, are you using sbt and `reStart`? In the wiki page linked above, there is some guide how to achieve some kind of "hot reload". You can edit the elm files and a script watches them, recompiles them and you then only need to refresh the page to see your changes. Use this until you see your text. Then run `sbt ";clean ;make ;make-zip"` at the end.

**Comment by DorimeDoge** [comment]
Hello

Oh so I did everything right and it should work? And can I just git clone repo again, put this code in it and it should work?

Thanks!

**Comment by eikek** [comment]
Yes! It should work like that.

**Comment by DorimeDoge** [comment]
Hello,

Maybe you have any simple (but works with sharry, like themes changing) page sources for Website Rules and Website Privacy Policy?

Thanks,

**Comment by eikek** [comment]
Hi @DorimeDoge I'm not sure if I understand :) Do you mean some guide that helps you create a new page?

**Comment by DorimeDoge** [comment]
Hello,

Yes, you can try to send me guide how to create new page (if only it will beat my small brain :D)

You know like mega.nz has some kind of ToS page (https://mega.nz/ios_terms.html). I want to make this for my website too. Like different page. And if you want to make that feature for sharry - sure! :)

Thanks!

**Comment by eikek** [comment]
I think the easiest way is to make it outside of sharry. I assume you have some proxy in front, like nginx, traefik or whatever? You can simply create a static html page somewhere and create a link to it in the welcome message? This way you don't need to edit the sources at all. Or you can add a link to the home page. This would only require to edit the `Page/Home/View.elm` file accordingly.

I don't have time to do a comprehensive writeup on this, sorry :/. But you could look at how the `Home` page is integrated. This is essentially only a page with text on it. Here are some other pointers that are interesting:

- [tailwind docs](https://tailwindcss.com/docs) tailwind is used for all styling. It is great!
- [elm intro](https://guide.elm-lang.org/)

**Comment by DorimeDoge** [comment]
Hello,

Thanks, but I think its more better and simpler to make everything in Elm and Scala. As I said I will try to draw you what you want :).

Pretty find if you dont want to work on that features :DDD.

**Comment by DorimeDoge** [comment]
Hello,

Here is a picture what I want to do:

![image](https://user-images.githubusercontent.com/57041295/126870140-f2b5b5e6-0a43-4020-a5fe-35e991543541.jpg)

Thanks!

**Comment by DorimeDoge** [comment]
Hello,

Any ideas how could I fix this?

![image](https://user-images.githubusercontent.com/57041295/126873499-703011d9-001d-48db-af04-d8bb7d36e2ee.png)

Thanks!

**Comment by eikek** [comment]
The first is clearly a bug! (I thought that I fixed this but it seems not :-)). We should create a separate ticket for this. It can be fixed in `App/View.elm` line 52 - we need to check for `acc.success`.

The second is possible, but I need to look into it. We can create an issue for this, too.

**Comment by DorimeDoge** [comment]
Hello,

Ok I am going to close this one and open other 2!

Thanks!
