### ISSUE TITLE
[BUG] Login Failed

### ISSUE THREAD

**Issue by DorimeDoge** [eikek/sharry#507]
Hello,

I found a bug! When you login and you just press "Login" with empty boxes or wrong password and etc. You get view like this:

![image](https://user-images.githubusercontent.com/57041295/126874819-5e82c83a-71d0-41c2-a51d-7e5a93b233eb.png)

Please fix,
Thanks!

**Comment by eikek** [comment]
Thanks for reporting! I think this can be fixed in `App/View.elm` line 52 - we need to check for `acc.success`.

**Comment by DorimeDoge** [comment]
Hello,

How much does it take to you to fix bugs like these?

Thanks!

**Comment by eikek** [comment]
If I'm not mistaken here, this is an easy fix. It is only the view that didn't check the response for a successful login. There is already everything prepared for the `else` case. If you want, you can try to fix it?

**Comment by DorimeDoge** [comment]
Hello,

I can try to fix this but I think you as owner know better, and if you are going to fix it like tomorrow or after tomorrow (Monday) can you also add that big text in login page, because I cant make it work :(

Thanks!

**Comment by eikek** [comment]
I won't have time for this for a while. But I'll fix it for the next release.

**Comment by DorimeDoge** [comment]
Hello,

Ah not good. Could you explain me how I can try to fix it by myself? 

Thanks!

**Comment by eikek** [comment]
Hello @DorimeDoge I added a hint in the first comment above. I don't have time to guide you step by step, this takes even more time then fixing it myself. Please experiment a bit on your own. The translation guide also has some tips on setting up the project  for working on the client. I know this is a bug, but I consider it a minor one. It is only the view and only if the password is wrong. Shouldn't be a big deal actually!

**Comment by DorimeDoge** [comment]
Hello,

Oh okay I will try, could you check my other feature?

Thanks!

**Comment by DorimeDoge** [comment]
Hello,

I need some help with page editing, I want this:

![image](https://user-images.githubusercontent.com/57041295/126910371-068df048-020d-47cf-907f-388f413e84f6.png)

To be like: "[Login](http://localhost:9090/app/login) or [Register](http://localhost:9090/app/register) to this cool website."

Can you explain how to do this?
Thanks!

**Comment by DorimeDoge** [comment]
Hello,

This is what I got so far:

[Code](https://pastebin.com/kQfwHrqs)

But I dont know how to add second link. Can you help me little bit?

Thanks!

**Comment by eikek** [comment]
It looks ok, I think you miss a `a` function after the `span`. I really recommend going through the [elm guide](https://guide.elm-lang.org/) - it is really useful and not much. Also, [this book](https://elmprogramming.com/model-view-update-part-1.html#view) seems nice, too.

**Comment by DorimeDoge** [comment]
Hello,

Thanks for everything. Can I also get your Matrix user id?

Thanks!

**Comment by eikek** [comment]
Sure, it's @eikek:matrix.org

**Comment by DorimeDoge** [comment]
Hello,

I updated the code as you said:

[Code](https://pastebin.com/9KyuWeRV)

But still cant make it work. Any ideas?

Thanks!

**Comment by eikek** [comment]
Well done :-)
