### ISSUE TITLE
[FEATURE] Only Login/Register

### ISSUE THREAD

**Issue by DorimeDoge** [eikek/sharry#508]
Hello,

I want to suggest feature! When you login/register you cant go to home or other pages. Like by pressing this:

![image](https://user-images.githubusercontent.com/57041295/126874881-fdb3d0b9-7f3d-4e85-935f-84f31a7be7e6.png)

But also would be great if member doesnt has an account, they get redirected to login/register page. For example: Someone send you link like http://localhost/app/home, person gets redirected to login/register page if doesnt has an account!

Thanks!

**Comment by eikek** [comment]
Thanks for this suggestion.

>  For example: Someone send you link like http://localhost/app/home, person gets redirected to login/register page if doesnt has an account!

This already works "on my machine" - doesn't it for you?

**Comment by DorimeDoge** [comment]
Hello,

No, it doesnt work for me :/

Thanks!

**Comment by eikek** [comment]
I don't know, but I'm using 1.8.0. If I type in my browser `/app/home` I get redirected to the login page.

**Comment by DorimeDoge** [comment]
Hello,

Dont worry, I will check and inform you. :)

Thanks!

**Comment by DorimeDoge** [comment]
Hello, Yes you are right if you go to `/app/home` you get redirected to the login page. (Even on 1.9.0), but when you are in login page and press this icon:

![image](https://user-images.githubusercontent.com/57041295/126893409-b27cd547-092a-4a55-ab39-0f9457d474ee.png)

You get redirected to home page. Is it possible that you cant get redirected to home page if you are in login page and dont have account?

Thanks

**Comment by DorimeDoge** [comment]
Hello,

I think I have better idea, if I get that working I am fine with that, but if I wont I will reopen this.

Thanks!
