### ISSUE TITLE
Docker installation throws error when uploading file

### ISSUE THREAD

**Issue by fboterblom** [eikek/sharry#519]
Hello,
I have a running docker installation. When i upload a file to the share it stays at 0% and after a while throws the error:

Error: tus: failed to resume upload, caused by [object ProgressEvent], originated from request (response code: 0, response text: )

**Comment by fboterblom** [comment]
yes i downloaded your repo (GIT clone) and started it up on my Qnap.

**Comment by eikek** [comment]
And the sharry.conf has not been changed? What is the url that you use to access it? Can you try using the ip address? Another thing that may be helpful: can you open dev tools in your browser (it's Shift+F12 on firefox), go to the network tab. Then click submit and look at the new entries. I think the upload goes for some reason not to the server.

**Comment by fboterblom** [comment]
Nothing changed in the sharry.conf, only changed the port number in docker-compose.yml at the host site.
192.168.10.55:9099 is the url I use.
When looking in firefox and using dev tools i see: NS_ERROR_DOM_BAD_URI

**Comment by fboterblom** [comment]
ah , its because of the port change in docker-compose.yml....

**Comment by fboterblom** [comment]
anyway to change to port number at docker side?

**Comment by fboterblom** [comment]
ok changed port in sharry.conf and in the docker-compose.yml. This worked.

**Comment by eikek** [comment]
Oh interesting! THanks for the update. What did you change exactly to make it work? Is there a mismatch in the compose file vs. sharry.conf that needs to be fixed?

**Comment by fboterblom** [comment]
Yep, so we can close this issue
