### ISSUE TITLE
Feature: configurable default validity

### ISSUE THREAD

**Issue by stonor** [eikek/sharry#521]
Looks like default validity (2 days) is hardcoded here:

https://github.com/eikek/sharry/blob/d335f1af3e5ed87bb7241a014820fb0bf6c849c3/modules/webapp/src/main/elm/Data/ValidityOptions.elm#L51

It would be great to expose that parameter in the conf file.

**Comment by eikek** [comment]
Yes, true! Also the maximum validity is in the config file, but not transported to the client.

**Comment by stonor** [comment]
Thanks for a quick reply. Sharry rocks.
