### ISSUE TITLE
Feature: "Receive files from others" block on frontpage

### ISSUE THREAD

**Issue by stonor** [eikek/sharry#522]
I think the Alias functionality is a bit hidden in the burger menu. Why not add a "Receive files from others" block on frontpage with a button to add an Alias page. There is plenty of room.

**Comment by eikek** [comment]
Yes, good idea! Do you mean a specific alias page or the list of aliases? I'd think the same link as in the burger menu, right?

**Comment by stonor** [comment]
Wow, quick answer!

Yep same link or maybe correspondent buttons to the Shares:

Create Alias | View Aliases
