### ISSUE TITLE
504 error behind when behind Nginx Proxy Manager

### ISSUE THREAD

**Issue by fboterblom** [eikek/sharry#534]
I changed the sharry config to work behind my Nginx Proxy manager but all i get is 504 error after a timeout period from the proxy server.
As i am running in a docker container i am not sure what bind address to use so i went for 0.0.0.0. Also placed the base url into the config (changed it for security reasons):

sharry.restserver {

  base-url = "https://sharry.mydomain.com"

  bind {
    address = "0.0.0.0"
    port = 9099
  }

  backend {
    auth {
      fixed.enabled = true ## enabled admin:admin access
    }

    jdbc {
      url = "jdbc:postgresql://db:5432/dbname"
      user = "dbuser"
      password = "dbpass"
    }

    signup {
      mode = "open"
      invite-time = "14 days"
      invite-password = "generate-invite"
    }
  }

}

**Comment by eikek** [comment]
Hi @fboterblom , the 504 means that nginx didn't get any response from the sharry server. Can the machine running nginx reach the sharry server? In your config you assigned sharry port 9099.  Could it be that you forgot to expose this port in the container? It is really hard to tell what's wrong exactly. You need to make sure that you can connect to the sharry server inside the container. Do you use docker-compose or something like that?
