### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [eikek/sharry#543]
Few potential security vulnerability has been disclosed to huntr .
Plz validate report submitted against your repo  by going huntr https://huntr.dev/
you should have received report magick  link to view the details in your mailbox 
report url
https://huntr.dev/bounties/16b755fd-1cc5-43d2-9876-935e40dfe4e2/
https://huntr.dev/bounties/12eb233e-ddeb-40c3-9c07-6bd4464d7f6c/
https://huntr.dev/bounties/744505c5-8c68-4001-ac1a-09d28a52789c/

**Comment by eikek** [comment]
Hi @ranjit-git , I'm a bit confused, why a another company is involved. I don't want to register anywhere. I'd prefer issues here on github.

**Comment by ranjit-git** [comment]
Hunte is a opensource bugbounty platform. 
You don't need to register there to validate the report . 
You had given security email address in your securty.md file. 
Huntr already sent a magick link to your provided mail address to view the report details. 
Using that magick link you can validate report without sign up. 
Plz let me know if you don't received that mail then I will ask team to send again

**Comment by ranjit-git** [comment]
In your mailbox just search for "huntr" Keyword to list all report mail

**Comment by eikek** [comment]
so I found these mails and confirmed the issues. one has been fixed already. the others are not important to me.
