### ISSUE TITLE
sharry-restserver.bat not working at all

### ISSUE THREAD

**Issue by DJXJD** [eikek/sharry#563]
When running sharry-restserver.bat in the command line, I get the following errors:
"The input line is too long.
The syntax of the command is incorrect."

Any help would be much appreciated as sharry seems like an awesome application!

**Comment by eikek** [comment]
Hi @DJXJD - oh I'm sorry :/ I don't have any windows to test this. The bat file is generated by a (popular) build plugin. Maybe the command is indeed to long? Is there any more specific message? I'm afraid I can't help you with windows specific stuff. An alternative would be to try the docker way - but no idea if windows can do that either.

**Comment by DJXJD** [comment]
Unfortunately there is no more specific message.

From the cursory googling I did, it might be the line that sets the classpath that's too long. Seeing as the bat file was generated by a build plugin, and a popular one at that, it could be that other people have experienced a similar issue with the bat files generated by that plugin. Maybe, and hopefully, it's a known issue that's being taken care of there?

As for docker on Windows, I think that would work. Based on what I read, it uses wsl (Windows subsystem for Linux) 2 in the backend. Although atm I'd rather be able to run Sharry natively than through docker 😅

**Comment by eikek** [comment]
https://sbt-native-packager.readthedocs.io/en/stable/recipes/longclasspath.html#long-classpaths there we go :) Thanks for reporting!

**Comment by eikek** [comment]
Hi @DJXJD the current nightly packages contain a change that should fix this problem. If you find some time to try it out and give feedback, would be great! Thanks!

**Comment by DJXJD** [comment]
Would you look at that, it works perfectly! Thank you very much 😁!
