### ISSUE TITLE
fab fa-github not rendered

### ISSUE THREAD

**Issue by frafra** [eikek/sharry#570]
OAuth2 docs suggest to use "fab fa-github" as icon for GitHub, which does not show any icon.

**Comment by eikek** [comment]
Ah yes… sorry. This is because  the css gets minized. Hm not sure, maybe I can list a few brand icons to not remove on minimize.

**Comment by frafra** [comment]
I wonder if it could be possible to enable/disable the "fa" stylesheet from the settings file as a whole; "fa" icons could also be used in the footer, and it could be problematic to pick a good set of common brands icon to not remove. That could allow the use of other icons for non-common providers.

**Comment by eikek** [comment]
Yes you're right. It is not really a solution to pick a few random icons. It's better to include the whole fontawesome set. Or maybe just the openid icon. I guess no one really uses more than one provider…?
