### ISSUE TITLE
Extra scroll bar appears when opening the "Validity" menu

### ISSUE THREAD

**Issue by frafra** [eikek/sharry#572]
It looks that `overflow-y-auto` class causes this extra horizontal scrollbar to appear.

![Screenshot 2021-09-15 at 13-49-11 Sharry](https://user-images.githubusercontent.com/4068/133428075-7ae50fd3-002e-449d-8780-f07e7145de8e.png)

**Comment by eikek** [comment]
Thanks for reporting! I didn't see it really in the screenshot; and I never realized it. If the field is opened a vertical scrollbar appears on the right. Maybe I can make the parent element's height the page height.

**Comment by frafra** [comment]
No problem, it is a pleasure to have such a quick feedback from a developer :)
In my case (Firefox 92 under Windows 10) it has been enough to drop the `overflow-y-auto`, but I am not sure if that is the right way to do that. Having the container filling the whole page seems better :)
