### ISSUE TITLE
Mailadress autofill

### ISSUE THREAD

**Issue by CryoRig** [eikek/sharry#601]
Is there a way to autofill the mail address for users with oauth login?

Also, is there a way to define the username translation?
My oauth provider returns a mail address as user eg name.family@domain.com but Sharry displays it as namefamily@domain

**Comment by eikek** [comment]
I think the first part is already filed here #571 ?

There is currently no way to hook into the translation. Currently some characters are removed that are not allowed in a username - but I think I can change this to allow dots to be able to reuse this name as is.

**Comment by CryoRig** [comment]
Yes, #571 is basically what i need.
Can you tell me where to enable the dot and .com manually until you make the commit?

**Comment by eikek** [comment]
I think you need to change line https://github.com/eikek/sharry/blob/282e90d520b5c8fe66c567c6eebd4cff219e9d7f/modules/restserver/src/main/scala/sharry/restserver/routes/LoginRoutes.scala#L71

```scala
            NewAccount.create(u ++ Ident.atSign ++ p.id, AccountSource.OAuth(p.id.id))
```

and only use `u` and remove all the concatenation. This is only from the top of my head though…

**Comment by eikek** [comment]
Closing, email is filled in now and dots are also allowed in user names.
