### ISSUE TITLE
first load, app not working and lot of console errors

### ISSUE THREAD

**Issue by MichelBaie** [eikek/sharry#631]
Hi,
I just tried to setup my instance of sharry. But after i log in, the first time the page load, buttons aren't working and lot of errors are comming into the dev console.
After ctrl+f5, everything is working fine.
![image](https://user-images.githubusercontent.com/39345534/141682105-dfe26975-5519-4d44-8cf4-4719642c1344.png)

**Comment by eikek** [comment]
Hi @MichelBaie - this could be related to a browser plugin. Do you have browser plugins running? Could you try with a different browser without any plugins to see if that is different?

**Comment by MichelBaie** [comment]
I tried many browsers, they all had adblock, but only cloudflare things were blocked.
I also disabled cloudflare ameliorations.

But i will reinstall it tomorrow with only letsencrypt and no plugins on my browser.

**Comment by eikek** [comment]
Hm, okay adblock shouldn't be a problem. Only extensions that mess with the dom. (Also there shouldn't be any cloudflare/external things to be downloaded at all.) I currently suspect there is some browser extension that somehow changes the dom, which is not supported. The frontend needs to own it exclusively.

**Comment by MichelBaie** [comment]
Here is a clean install, without any configuration.

![image](https://user-images.githubusercontent.com/39345534/141798256-b43a8009-41cb-4c05-af81-72d45f556c77.png)
![image](https://user-images.githubusercontent.com/39345534/141798334-889a3d36-ea79-4573-9027-7d356ea4b377.png)

I'm using firefox in private navigation without extensions
Maybe you will have the same error ? https://send.creepercreep.fr ?

**Comment by eikek** [comment]
Wow, really strange! I see it here, too. But my own install works just fine. You are also on version 1.9.0 right?

There is something in the network tab, that looks very suspicious to me: there are requests from the site to some cdn, POST and GETs. It downloads some javascript into the site. Maybe this is messing with the dom then.

![Selection_279](https://user-images.githubusercontent.com/701128/141807128-e2442944-e935-4f52-92c1-ead2a84d11aa.png)

**Comment by MichelBaie** [comment]
I'm using cloudflare, but i disabled any ameliorations for my website.
These scripts are for analytics, let me try without cloudflare :thinking:

**Comment by eikek** [comment]
Closing now, you can always reopen or come back with new issues.
