### ISSUE TITLE
Feature Request: Config Setting for OAuth Logout URL

### ISSUE THREAD

**Issue by pellux-network** [eikek/sharry#726]
Currently, it seems that the logout button is always set to #. For OAuth authentication, I ended up editing line 29650 of sharry-app.js on version 1.9.0:

`$elm$html$Html$Attributes$href('#'),`

to my OAuth logout endpoint with the proper query string and it worked a treat. For better usability I would suggest adding this as a config option in sharry.conf, probably logout-url = "[Logout Endpoint]"

**Comment by eikek** [comment]
But wouldn't that mean that when you logout on sharry you are logged out on every other application/site you are using through your identity provider?

**Comment by thcrt** [comment]
> But wouldn't that mean that when you logout on sharry you are logged out on every other application/site you are using through your identity provider?

When you're using OIDC for SSO, that's exactly the point. Right now, logging out of the identity provider will leave me logged in to Sharry with no way to log out besides clearing my cookies, and Sharry gives no option in its UI to log out of the identity provider.
