### ISSUE TITLE
Feature Request: Default image preview setting/disable file download

### ISSUE THREAD

**Issue by kimxdhaha** [eikek/sharry#778]
Hi I just started using sharry and mainly use it for image sharing for some personal project. 

When someone open the share link & click the filename its initial the download, im wondering is it possible to make it imgur like one page infinie scroll across all the images or at least can disable the file download function and just preview. Many thanks.

**Comment by eikek** [comment]
Hi, thanks for the suggestion. I remember some time ago I made the fliename initiate the download from a user request :) Sharry is not really special to images - but maybe it is possible to have the "card view" as default view. Would this improve your situation?

**Comment by kimxdhaha** [comment]
Thanks for your reply, filename to initiate download is a nice touch tho, instead of card viewas default view i will prefer having a toggle can set preview mode as default. I know that sharry ia not special to images but out there images sharing with max view limit is will rare so that will be great if it can add that feature!

**Comment by eikek** [comment]
Ah you mean not the card view, but rather the "big image viewer" mode?

**Comment by kimxdhaha** [comment]
Exactly, that will be awesome:)

**Comment by kimxdhaha** [comment]
Thanks for your time, just brought you a coffee!
