### ISSUE TITLE
Upload just sitting there without completing

### ISSUE THREAD

**Issue by ybizeul** [eikek/sharry#796]
![image](https://user-images.githubusercontent.com/182035/174458928-f5639a2c-6a2f-42f1-b60f-cc3079aab8df.png)

In admin page I see this :

![image](https://user-images.githubusercontent.com/182035/174458941-b1310383-27df-43e0-9e0b-80f6459668cb.png)

At this point, database seems to be corrupted and recovered on next reboot.
Sharry is deployed in a kubernetes cluster backed by a NFS PVC if that matters.

Smaller files, like 473MB seems to be ok. Is there an absolute max file size ?
Changing chunk size to 2M seems to help, but still takes quite some time to validate the upload.

**Comment by eikek** [comment]
Hi, there is a max-size option, but from the screenshot I think you already set it to 5G. The reason for the long wait could be calculating the checksum of the file, which as done after uploading is complete. I had plans to asynchronous do this calculation… if I just had more time.

If changing the chunksize to 2m makes a difference, then this sounds like a bug, 🤔 . When you do the upload and open developer console in the browser - are there any failed requests?

**Comment by ybizeul** [comment]
I start to think NFS backend is the issue. The database seems to randomly become unresponsive, sometime I get an error in the lock saying it's been trying to 30s, but not always.
When this happens, I can't even list shares, but there is no error eithe rin the browser logs or the container logs.

It's been a while since I wanted to implement a block CSI on my kubernetes cluster so I guess I'll have to get to it. I'll report my findings

**Comment by ybizeul** [comment]
What is the checksum algorithm by the way ?

**Comment by ybizeul** [comment]
Here is one thing : after a while, the sharry logs are flooded with this :
```
2022.06.20 09:04:44:0006 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 PATCH /api/v2/sec/upload/9rmU7qsrBLq-LaFTnugoPu4-qwBrFRrK63S-J62AoY48vn5/files/tus/52tBMqS9rHx-MU4pDnwk17C-q56e84MFV2G-66opC5SGum
2022.06.20 09:04:44:0007 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 204 No Content
2022.06.20 09:04:43:0020 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 PATCH /api/v2/sec/upload/9rmU7qsrBLq-LaFTnugoPu4-qwBrFRrK63S-J62AoY48vn5/files/tus/52tBMqS9rHx-MU4pDnwk17C-q56e84MFV2G-66opC5SGum
2022.06.20 09:04:43:0021 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 204 No Content
2022.06.20 09:04:44:0008 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 PATCH /api/v2/sec/upload/9rmU7qsrBLq-LaFTnugoPu4-qwBrFRrK63S-J62AoY48vn5/files/tus/52tBMqS9rHx-MU4pDnwk17C-q56e84MFV2G-66opC5SGum
2022.06.20 09:04:44:0009 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 204 No Content
2022.06.20 09:04:43:0022 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 PATCH /api/v2/sec/upload/9rmU7qsrBLq-LaFTnugoPu4-qwBrFRrK63S-J62AoY48vn5/files/tus/52tBMqS9rHx-MU4pDnwk17C-q56e84MFV2G-66opC5SGum
2022.06.20 09:04:43:0023 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 204 No Content
2022.06.20 09:04:44:0016 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 PATCH /api/v2/sec/upload/9rmU7qsrBLq-LaFTnugoPu4-qwBrFRrK63S-J62AoY48vn5/files/tus/52tBMqS9rHx-MU4pDnwk17C-q56e84MFV2G-66opC5SGum
2022.06.20 09:04:44:0017 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 204 No Content
2022.06.20 09:04:44:0010 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 PATCH /api/v2/sec/upload/9rmU7qsrBLq-LaFTnugoPu4-qwBrFRrK63S-J62AoY48vn5/files/tus/52tBMqS9rHx-MU4pDnwk17C-q56e84MFV2G-66opC5SGum
2022.06.20 09:04:44:0011 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 204 No Content
2022.06.20 09:04:43:0024 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 PATCH /api/v2/sec/upload/9rmU7qsrBLq-LaFTnugoPu4-qwBrFRrK63S-J62AoY48vn5/files/tus/52tBMqS9rHx-MU4pDnwk17C-q56e84MFV2G-66opC5SGum
```

Which don't seem so different than regular transfer logs. I'm now running the DB on block storage

**Comment by eikek** [comment]
Oh NFS - I remember difficulties with it as well, but a few years ago…. The symptoms you describe would make sense from what I can recall. Btw, which database are you using over nfs - H2? 

Sharry does a sha256 checksum of each file uploaded. This requires to read the entire file once and it can't be done while uploading either, so currently means to wait at the end of the upload. But I think this is a nice to have only and nothing mandatory so it could be calculated asynchronously, or even not at all.

The logs you just posted look actually fine to me. Sharry sends PATCH requests when uploading. Flooding whith these is of course strange.  Something is not working correctly, I guess - or the chunksize is really small. What does "corrupt" mean exactly? Is it not completely uploaded or scrambled? If you reload the page while uploading, then the upload stops ofc… then you could try to upload the same file again to complete it. Also just be be sure: you are on Sharry 1.9.0?

**Comment by ybizeul** [comment]
My chunk size is now back to 512K.
It does not seem I have a way to complete the download, I think I have to remove and re-upload :
![image](https://user-images.githubusercontent.com/182035/174575786-dfaeae34-1271-4f98-b4b8-ed17d9a681ca.png)

That's Sharry 1.10.0

**Comment by ybizeul** [comment]
I'm trying to re-upload, but it's stuck a 1%. I think it's another case of the database connection behing broken. It's now H2 on file on a block volume over iSCSI

**Comment by eikek** [comment]
Hm, I think I need to try to reproduce it - hard to say from remote. I would also assume a db connection problem. For comparison maybe you could try on a local (like `/tmp/`) directory to remove the network? And there are no errors in the logs either?

**Comment by eikek** [comment]
Just came to mind: in sharry 1.10.0 there was a  new library introduced for storing files. So it might be worth a try with sharry 1.9.0 - if that makes a difference. It's not very likely from my pov, but I was surprised a few times before :)

**Comment by ybizeul** [comment]
Logs are much more verbose, I see one line for each 10M of file, and I don't think it's just because of the additional "DEBUG" like. It seems to output more lines during the transfer, which make more sense to me as I'm local and transfers are relatively quick. From a UI perspective the transfer doesn't seem to take less time though

I also had to delete data as the database wouldn't backward compatible, which makes sense

Checksum computation was much faster too (~2/4min for a 4.48GB file) but CPU no ore than 4% which can probably be explained by 1Gbit link to connect to the LUN as it has to read the whole file.

On second upload, it stalled at around 93% for a couple minutes then continued

Third got stuck at 1%, I paused and resumed, and it kept going though rather slow, but at some point during the transfer, used space on the lun freed up, so I'm thinking maybe it was stuck while garbage collecting.

Also deleting file doesn't seem to reclaim space immediatly, is there a scheduled garbage collection ?

Overall much better experience

**Comment by ybizeul** [comment]
Went back to NFS and gave it a shot with 1.9, works fine as well, I couldn't break it. I can certainly do more tests for 1.10 if you need.

**Comment by eikek** [comment]
Hi @ybizeul sorry for the delay. I think when the upload hangs for a while and then continues this is most likely a connection issue. The client is prepared for that and retries a few times and will eventually give up. I would not think that gargabe collecting is the cause for stuck uploads, it is only taking millis at most. It might be when you assigned very low heap and the GC is kicking in all the time. If that is the case you can try lowering the chunksize maybe. But this increases upload/download time. I can see here it uses about ~100M heap when uploading in 1M chunks (GC is not kicking in because I have plenty ram :)).

Regarding reclaiming space: what dbms are you using? I don't think any dbms frees the space of deleted sutff, because it usually is a costly operation and the space will be simply reused. On postgres you can run vacuum periodically to do this (there is an auto-vacuum provided). I think the others have similar things, but I don't know.

I'm know working on moving the sha computation out of the upload, it will be done asynchronously. This is better anyways for large files especially on not so beefy devices.
