### ISSUE TITLE
CLI Client

### ISSUE THREAD

**Issue by TheSunCat** [eikek/sharry#849]
Hi! I found this project and love the web interface. I would like to use my sharry server to automatically upload screenshots and videos to that I would like to share. For this I would have to be able to upload files from the command line. I found issue #14, which adds a CLI client, but it seems to no longer be a part of this project. Is there a currently existing/maintained CLI client for sharry?

**Comment by eikek** [comment]
Hi @TheSunCat you're right, the cli is not part of the project anymore. It was too much work to maintain it as well and not sure if it was used much. But you can achieve this using a custom script with `curl`, it's not very hard. An example for an upload (via an alias) is [here](https://eikek.github.io/sharry/doc/rest#upload-a-file-to-the-new-alias-page) - you can add more files usig `-F` multiple times.
