### ISSUE TITLE
Change the logo 

### ISSUE THREAD

**Issue by mr-biggles** [eikek/sharry#853]
Hello, I wanted to change the logo of sharry by those of my company, 

I went in Sharry.conf and I added the link in HTTP http://Myip/logo.png 

on the lines app-icon and app-logo

but unfortunately I get this result after restarting sharry.

Do you have the procedure to change the logo please? 

![image](https://user-images.githubusercontent.com/92831318/186457226-1eee0ecf-e4e6-49b5-91b0-362e0f0fffca.png)
![image](https://user-images.githubusercontent.com/92831318/186457835-602d3e15-176b-4b5c-94db-aeceb3764637.png)

Sorry for the questions, maybe it's stupid but it's the first time I install this kind of application, especially in docker :)

**Comment by eikek** [comment]
Hi @mr-biggles , no worries. It could be that your sharry is reachable via https but your image url shows to be http only. Maybe that's the problem? Otherwise: you are sure that the image-url is working fine? In the browser you can open developer-tools and look at the url that has been rendered in the html - maybe there is some typo or the url cannot be reached from the browser?

**Comment by mr-biggles** [comment]
Thank you for this very quick answer :) 

my image is well hosted on an ftp accessible only in http
I did the test to access sharry directly and the images are displayed perfectly :).
It is my reverse proxy that prevents me from displaying the images.

Do you know if I can modify the files (logo) directly in the container? 

Without going through a third party ftp?

Access in http directly on the application
![image](https://user-images.githubusercontent.com/92831318/186459786-40e48df4-e62e-4068-ac21-a1a1e54213c0.png)

Access in https via reverse proxy
![image](https://user-images.githubusercontent.com/92831318/186459943-de5419c2-aa05-4b41-bbde-a5335d5a6a87.png)

**Comment by eikek** [comment]
> Do you know if I can modify the files (logo) directly in the container?
> 
> Without going through a third party ftp?

It might be possible, but I've never tried :) if you use an url `file:///path/to/the/image.png` - this _could_ work. You need to put the file somewhere into the local file system. Another option could be to host the logo on sharry itself - you can publish the share (maybe upload it as admin user or something) and get the public link to the file directly.
