### ISSUE TITLE
Feature Request: Generic OIDC

### ISSUE THREAD

**Issue by tmeuze** [eikek/sharry#889]
Hello, thanks for the project!

I'm curious if you have any plans to support generic OpenID providers? Specifically, I am using [Authentik](https://goauthentik.io/). 

This provider exposes [GitHub Enterprise compatible endpoints](https://goauthentik.io/docs/providers/oauth2/#github-compatibility), but this setup results in `The request body was malformed.` for me.

Thank you.

**Comment by eikek** [comment]
Hi @tmeuze , I'm not sure if I understand really. There should be "generic" oidc support as far as I can tell. You can configure the endpoints to use for the auth and tokens and optional a user endpoint to get the account information from. But when authentik provides a github compatible flavor, this should actually also work. OTOH you can configure it quite freely (see [this](https://eikek.github.io/sharry/doc/configure#oauth)). Is there anything concretely you need?

**Comment by tmeuze** [comment]
Hi @eikek , I'm sorry for the delay. 

I suppose my requesting a 'generic' provider was misinformed. I'm not sure how to further debug why the Github provider doesn't work, however. The debug logs only show:
```
2022.11.23 13:52:44:0003 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v2/open/auth/oauth/github/resume?code=cdf43f3b93a549d69132aea2581af959&state=
2022.11.23 13:52:44:0004 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - service raised an error: class org.http4s.MalformedMessageBodyFailure
2022.11.23 13:52:44:0002 [io-comp...] [DEBUG] org.http4s.server.message-failures - Message failure handling request: GET /api/v2/open/auth/oauth/github/resume from 10.0.1.1
```
And I just land at a page: `api/v2/open/auth/oauth/github/resume?code=<code>&state=`, with the malformed body error. Authentik shows the application was authorized. 

Maybe I should be asking this in the Authentik support channels instead - but it seems like it's working properly.

**Comment by eikek** [comment]
Hey @tmeuze - this error means that sharry could not read the json returned from the openid provider. Hm, can you share your openid config on sharry?
