### ISSUE TITLE
External upload not working

### ISSUE THREAD

**Issue by VitusE** [eikek/sharry#969]
Hi eikek,

thanks, I really like sharry. It is exactly what I needed for my wedding. Guest should be able to upload their pictures and videos in high quality (not via whatsapp or whatsoever). 

I'm using noip.com for a DNS (zuhausebistdu.ddns.net) which points to my public IP. Configured Port forwarding on my router. 
Base-URL is configured as "zuhausebistdu.ddns.net" as well. 
As I said, I can access sharry, but can't upload a file. 

Although I managed to get access to the webpage and I cannot upload a file. The Server accepts the upload and I can see the new entry/share in the list. But on my phone for example the upload stays at 0%. 
When I'm in the same network as my Pi, I also cant upload with "zuhausebistdu.ddns.net", but the upload works with the IP adress of my Pi/sharry.
Is there any configuration I'm missing? Is a reverse IP neccessary for external access?

**Comment by eikek** [comment]
Hi @VitusE thanks! I think you need to change the `base-url` setting. It should define the public url to sharry. It is used by the server to create cookies which are tied to a domain. So probably it is `https://zuhausebistdu.ddns.net` (the default is `http://localhost:9090`). You should find it in the config file.

**Comment by VitusE** [comment]
Hi, I‘ll try the config. Is there something I need to do after I changed the config? I guess reboot my Pi?

**Comment by eikek** [comment]
Yes, you only need to restart sharry, but rebooting then also works
