### ISSUE TITLE
Using filestore and deleting an upload, leaves the uppermost directory on the filesystem

### ISSUE THREAD

**Issue by electrofloat** [eikek/sharry#975]
When using a filestore and uploading a file a directory structure created with the file chunk in it:
`sharry_data/2q/2qmSjn2Jo1k-UzFrasLWBsE-rYG5vnk3Dtx-CPzKzaFvWzh/chunk_00000000`

when the file is deleted on the web interface, it leaves the uppermost directory on the filesystem, with the above example:
`sharry_data/2q/`

it should have deleted `2q` too.

**Comment by eikek** [comment]
Thanks for reporting. Yes this needs to be cleaned up
